// Generated by scripts/build-stations.rb. Sources: data/stations.md.
export const STATIONS = Object.freeze([
  {
    "name": "서울역",
    "lines": [
      "1호선",
      "4호선",
      "경의중앙선"
    ],
    "sourceIds": [
      "0150",
      "0426",
      "1001",
      "1251"
    ],
    "coordinates": [
      126.97103,
      37.557231
    ],
    "id": "station-0150"
  },
  {
    "name": "시청",
    "lines": [
      "1호선",
      "2호선"
    ],
    "sourceIds": [
      "0151",
      "0201"
    ],
    "coordinates": [
      126.977088,
      37.565715
    ],
    "id": "station-0151"
  },
  {
    "name": "종각",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "0152"
    ],
    "coordinates": [
      126.982923,
      37.570161
    ],
    "id": "station-0152"
  },
  {
    "name": "종로3가",
    "lines": [
      "1호선",
      "3호선",
      "5호선"
    ],
    "sourceIds": [
      "0153",
      "0319",
      "2535"
    ],
    "coordinates": [
      126.991791,
      37.571605
    ],
    "id": "station-0153"
  },
  {
    "name": "종로5가",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "0154"
    ],
    "coordinates": [
      127.001849,
      37.570926
    ],
    "id": "station-0154"
  },
  {
    "name": "동대문",
    "lines": [
      "1호선",
      "4호선"
    ],
    "sourceIds": [
      "0155",
      "0421"
    ],
    "coordinates": [
      127.009287,
      37.57093
    ],
    "id": "station-0155"
  },
  {
    "name": "신설동",
    "lines": [
      "1호선",
      "2호선"
    ],
    "sourceIds": [
      "0156",
      "0246"
    ],
    "coordinates": [
      127.024932,
      37.574747
    ],
    "id": "station-0156"
  },
  {
    "name": "제기동",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "0157"
    ],
    "coordinates": [
      127.034893,
      37.578103
    ],
    "id": "station-0157"
  },
  {
    "name": "청량리",
    "lines": [
      "1호선",
      "경의중앙선"
    ],
    "sourceIds": [
      "0158",
      "1014"
    ],
    "coordinates": [
      127.044585,
      37.579956
    ],
    "id": "station-0158"
  },
  {
    "name": "동묘앞",
    "lines": [
      "1호선",
      "6호선"
    ],
    "sourceIds": [
      "0159",
      "2637"
    ],
    "coordinates": [
      127.015653,
      37.572279
    ],
    "id": "station-0159"
  },
  {
    "name": "을지로입구",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0202"
    ],
    "coordinates": [
      126.982618,
      37.566014
    ],
    "id": "station-0202"
  },
  {
    "name": "을지로3가",
    "lines": [
      "2호선",
      "3호선"
    ],
    "sourceIds": [
      "0203",
      "0320"
    ],
    "coordinates": [
      126.992548,
      37.566672
    ],
    "id": "station-0203"
  },
  {
    "name": "을지로4가",
    "lines": [
      "2호선",
      "5호선"
    ],
    "sourceIds": [
      "0204",
      "2536"
    ],
    "coordinates": [
      126.997817,
      37.566595
    ],
    "id": "station-0204"
  },
  {
    "name": "동대문역사문화공원",
    "lines": [
      "2호선",
      "4호선",
      "5호선"
    ],
    "sourceIds": [
      "0205",
      "0422",
      "2537"
    ],
    "coordinates": [
      127.007885,
      37.565133
    ],
    "id": "station-0205"
  },
  {
    "name": "신당",
    "lines": [
      "2호선",
      "6호선"
    ],
    "sourceIds": [
      "0206",
      "2636"
    ],
    "coordinates": [
      127.016146,
      37.566154
    ],
    "id": "station-0206"
  },
  {
    "name": "상왕십리",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0207"
    ],
    "coordinates": [
      127.029354,
      37.564354
    ],
    "id": "station-0207"
  },
  {
    "name": "왕십리",
    "lines": [
      "2호선",
      "5호선",
      "경의중앙선"
    ],
    "sourceIds": [
      "0208",
      "1013",
      "2541"
    ],
    "coordinates": [
      127.037059,
      37.56184
    ],
    "id": "station-0208"
  },
  {
    "name": "한양대",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0209"
    ],
    "coordinates": [
      127.043655,
      37.555273
    ],
    "id": "station-0209"
  },
  {
    "name": "뚝섬",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0210"
    ],
    "coordinates": [
      127.047367,
      37.547184
    ],
    "id": "station-0210"
  },
  {
    "name": "성수",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0211"
    ],
    "coordinates": [
      127.055961,
      37.544581
    ],
    "id": "station-0211"
  },
  {
    "name": "건대입구",
    "lines": [
      "2호선",
      "7호선"
    ],
    "sourceIds": [
      "0212",
      "2729"
    ],
    "coordinates": [
      127.071011,
      37.540786
    ],
    "id": "station-0212"
  },
  {
    "name": "구의",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0213"
    ],
    "coordinates": [
      127.085916,
      37.537077
    ],
    "id": "station-0213"
  },
  {
    "name": "강변",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0214"
    ],
    "coordinates": [
      127.094681,
      37.535095
    ],
    "id": "station-0214"
  },
  {
    "name": "잠실나루",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0215"
    ],
    "coordinates": [
      127.10379,
      37.520733
    ],
    "id": "station-0215"
  },
  {
    "name": "잠실",
    "lines": [
      "2호선",
      "8호선"
    ],
    "sourceIds": [
      "0216",
      "2815"
    ],
    "coordinates": [
      127.104338,
      37.514692
    ],
    "id": "station-0216"
  },
  {
    "name": "잠실새내",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0217"
    ],
    "coordinates": [
      127.086162,
      37.511687
    ],
    "id": "station-0217"
  },
  {
    "name": "종합운동장",
    "lines": [
      "2호선",
      "9호선"
    ],
    "sourceIds": [
      "0218",
      "4130"
    ],
    "coordinates": [
      127.076275,
      37.511426
    ],
    "id": "station-0218"
  },
  {
    "name": "삼성",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0219"
    ],
    "coordinates": [
      127.06316,
      37.508844
    ],
    "id": "station-0219"
  },
  {
    "name": "선릉",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0220"
    ],
    "coordinates": [
      127.048203,
      37.504286
    ],
    "id": "station-0220"
  },
  {
    "name": "역삼",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0221"
    ],
    "coordinates": [
      127.036456,
      37.500622
    ],
    "id": "station-0221"
  },
  {
    "name": "강남",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0222"
    ],
    "coordinates": [
      127.027912,
      37.49799
    ],
    "id": "station-0222"
  },
  {
    "name": "교대",
    "lines": [
      "2호선",
      "3호선"
    ],
    "sourceIds": [
      "0223",
      "0330"
    ],
    "coordinates": [
      127.014667,
      37.493961
    ],
    "id": "station-0223"
  },
  {
    "name": "서초",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0224"
    ],
    "coordinates": [
      127.007917,
      37.491897
    ],
    "id": "station-0224"
  },
  {
    "name": "방배",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0225"
    ],
    "coordinates": [
      126.997596,
      37.481426
    ],
    "id": "station-0225"
  },
  {
    "name": "사당",
    "lines": [
      "2호선",
      "4호선"
    ],
    "sourceIds": [
      "0226",
      "0433"
    ],
    "coordinates": [
      126.981544,
      37.476538
    ],
    "id": "station-0226"
  },
  {
    "name": "낙성대",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0227"
    ],
    "coordinates": [
      126.963693,
      37.47693
    ],
    "id": "station-0227"
  },
  {
    "name": "서울대입구",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0228"
    ],
    "coordinates": [
      126.952739,
      37.481247
    ],
    "id": "station-0228"
  },
  {
    "name": "봉천",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0229"
    ],
    "coordinates": [
      126.941892,
      37.482362
    ],
    "id": "station-0229"
  },
  {
    "name": "신림",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0230"
    ],
    "coordinates": [
      126.929715,
      37.484201
    ],
    "id": "station-0230"
  },
  {
    "name": "신대방",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0231"
    ],
    "coordinates": [
      126.913149,
      37.487462
    ],
    "id": "station-0231"
  },
  {
    "name": "구로디지털단지",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0232"
    ],
    "coordinates": [
      126.901401,
      37.485266
    ],
    "id": "station-0232"
  },
  {
    "name": "대림",
    "lines": [
      "2호선",
      "7호선"
    ],
    "sourceIds": [
      "0233",
      "2746"
    ],
    "coordinates": [
      126.894932,
      37.493243
    ],
    "id": "station-0233"
  },
  {
    "name": "신도림",
    "lines": [
      "1호선",
      "2호선"
    ],
    "sourceIds": [
      "0234",
      "1007"
    ],
    "coordinates": [
      126.891084,
      37.508961
    ],
    "id": "station-0234"
  },
  {
    "name": "문래",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0235"
    ],
    "coordinates": [
      126.89476,
      37.517933
    ],
    "id": "station-0235"
  },
  {
    "name": "영등포구청",
    "lines": [
      "2호선",
      "5호선"
    ],
    "sourceIds": [
      "0236",
      "2524"
    ],
    "coordinates": [
      126.89661,
      37.525706
    ],
    "id": "station-0236"
  },
  {
    "name": "당산",
    "lines": [
      "2호선",
      "9호선"
    ],
    "sourceIds": [
      "0237",
      "4113"
    ],
    "coordinates": [
      126.902809,
      37.533406
    ],
    "id": "station-0237"
  },
  {
    "name": "합정",
    "lines": [
      "2호선",
      "6호선"
    ],
    "sourceIds": [
      "0238",
      "2623"
    ],
    "coordinates": [
      126.913366,
      37.549209
    ],
    "id": "station-0238"
  },
  {
    "name": "홍대입구",
    "lines": [
      "2호선",
      "경의중앙선"
    ],
    "sourceIds": [
      "0239",
      "1264"
    ],
    "coordinates": [
      126.923708,
      37.55679
    ],
    "id": "station-0239"
  },
  {
    "name": "신촌",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0240"
    ],
    "coordinates": [
      126.936926,
      37.555131
    ],
    "id": "station-0240"
  },
  {
    "name": "이대",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0241"
    ],
    "coordinates": [
      126.946013,
      37.556733
    ],
    "id": "station-0241"
  },
  {
    "name": "아현",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0242"
    ],
    "coordinates": [
      126.956141,
      37.557345
    ],
    "id": "station-0242"
  },
  {
    "name": "충정로",
    "lines": [
      "2호선",
      "5호선"
    ],
    "sourceIds": [
      "0243",
      "2532"
    ],
    "coordinates": [
      126.9629,
      37.560236
    ],
    "id": "station-0243"
  },
  {
    "name": "용답",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0244"
    ],
    "coordinates": [
      127.050899,
      37.561904
    ],
    "id": "station-0244"
  },
  {
    "name": "신답",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0245"
    ],
    "coordinates": [
      127.046481,
      37.57004
    ],
    "id": "station-0245"
  },
  {
    "name": "도림천",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0247"
    ],
    "coordinates": [
      126.882768,
      37.514287
    ],
    "id": "station-0247"
  },
  {
    "name": "양천구청",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0248"
    ],
    "coordinates": [
      126.865819,
      37.512398
    ],
    "id": "station-0248"
  },
  {
    "name": "신정네거리",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0249"
    ],
    "coordinates": [
      126.852912,
      37.520074
    ],
    "id": "station-0249"
  },
  {
    "name": "용두",
    "lines": [
      "2호선"
    ],
    "sourceIds": [
      "0250"
    ],
    "coordinates": [
      127.038091,
      37.574028
    ],
    "id": "station-0250"
  },
  {
    "name": "지축",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "0309",
      "1949"
    ],
    "coordinates": [
      126.913917,
      37.648033
    ],
    "id": "station-0309"
  },
  {
    "name": "구파발",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "0310"
    ],
    "coordinates": [
      126.918821,
      37.636763
    ],
    "id": "station-0310"
  },
  {
    "name": "연신내",
    "lines": [
      "3호선",
      "6호선"
    ],
    "sourceIds": [
      "0311",
      "2615"
    ],
    "coordinates": [
      126.921038,
      37.619229
    ],
    "id": "station-0311"
  },
  {
    "name": "불광",
    "lines": [
      "3호선",
      "6호선"
    ],
    "sourceIds": [
      "0312",
      "2613"
    ],
    "coordinates": [
      126.92982,
      37.610553
    ],
    "id": "station-0312"
  },
  {
    "name": "녹번",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "0313"
    ],
    "coordinates": [
      126.935756,
      37.600927
    ],
    "id": "station-0313"
  },
  {
    "name": "홍제",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "0314"
    ],
    "coordinates": [
      126.943736,
      37.589066
    ],
    "id": "station-0314"
  },
  {
    "name": "무악재",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "0315"
    ],
    "coordinates": [
      126.950291,
      37.582299
    ],
    "id": "station-0315"
  },
  {
    "name": "독립문",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "0316"
    ],
    "coordinates": [
      126.957748,
      37.574571
    ],
    "id": "station-0316"
  },
  {
    "name": "경복궁",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "0317"
    ],
    "coordinates": [
      126.97353,
      37.575762
    ],
    "id": "station-0317"
  },
  {
    "name": "안국",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "0318"
    ],
    "coordinates": [
      126.985443,
      37.576477
    ],
    "id": "station-0318"
  },
  {
    "name": "충무로",
    "lines": [
      "3호선",
      "4호선"
    ],
    "sourceIds": [
      "0321",
      "0423"
    ],
    "coordinates": [
      126.99408,
      37.561207
    ],
    "id": "station-0321"
  },
  {
    "name": "동대입구",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "0322"
    ],
    "coordinates": [
      127.005602,
      37.559052
    ],
    "id": "station-0322"
  },
  {
    "name": "약수",
    "lines": [
      "3호선",
      "6호선"
    ],
    "sourceIds": [
      "0323",
      "2634"
    ],
    "coordinates": [
      127.010541,
      37.554867
    ],
    "id": "station-0323"
  },
  {
    "name": "금호",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "0324"
    ],
    "coordinates": [
      127.015872,
      37.548034
    ],
    "id": "station-0324"
  },
  {
    "name": "옥수",
    "lines": [
      "3호선",
      "경의중앙선"
    ],
    "sourceIds": [
      "0325",
      "1011"
    ],
    "coordinates": [
      127.017269,
      37.541684
    ],
    "id": "station-0325"
  },
  {
    "name": "압구정",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "0326"
    ],
    "coordinates": [
      127.028461,
      37.527072
    ],
    "id": "station-0326"
  },
  {
    "name": "신사",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "0327"
    ],
    "coordinates": [
      127.020114,
      37.516334
    ],
    "id": "station-0327"
  },
  {
    "name": "잠원",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "0328"
    ],
    "coordinates": [
      127.01122,
      37.512759
    ],
    "id": "station-0328"
  },
  {
    "name": "고속터미널",
    "lines": [
      "3호선",
      "7호선",
      "9호선"
    ],
    "sourceIds": [
      "0329",
      "2736",
      "4123"
    ],
    "coordinates": [
      127.004403,
      37.50598
    ],
    "id": "station-0329"
  },
  {
    "name": "남부터미널",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "0331"
    ],
    "coordinates": [
      127.016189,
      37.485013
    ],
    "id": "station-0331"
  },
  {
    "name": "양재",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "0332"
    ],
    "coordinates": [
      127.033902,
      37.484477
    ],
    "id": "station-0332"
  },
  {
    "name": "매봉",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "0333"
    ],
    "coordinates": [
      127.046769,
      37.486947
    ],
    "id": "station-0333"
  },
  {
    "name": "도곡",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "0334"
    ],
    "coordinates": [
      127.055452,
      37.490922
    ],
    "id": "station-0334"
  },
  {
    "name": "대치",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "0335"
    ],
    "coordinates": [
      127.063642,
      37.494612
    ],
    "id": "station-0335"
  },
  {
    "name": "학여울",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "0336"
    ],
    "coordinates": [
      127.070594,
      37.496663
    ],
    "id": "station-0336"
  },
  {
    "name": "대청",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "0337"
    ],
    "coordinates": [
      127.079532,
      37.493514
    ],
    "id": "station-0337"
  },
  {
    "name": "일원",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "0338"
    ],
    "coordinates": [
      127.08439,
      37.483681
    ],
    "id": "station-0338"
  },
  {
    "name": "수서",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "0339"
    ],
    "coordinates": [
      127.101907,
      37.487378
    ],
    "id": "station-0339"
  },
  {
    "name": "가락시장",
    "lines": [
      "3호선",
      "8호선"
    ],
    "sourceIds": [
      "0340",
      "2818"
    ],
    "coordinates": [
      127.117757,
      37.492245
    ],
    "id": "station-0340"
  },
  {
    "name": "경찰병원",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "0341"
    ],
    "coordinates": [
      127.12454,
      37.495918
    ],
    "id": "station-0341"
  },
  {
    "name": "오금",
    "lines": [
      "3호선",
      "5호선"
    ],
    "sourceIds": [
      "0342",
      "2558"
    ],
    "coordinates": [
      127.127938,
      37.502057
    ],
    "id": "station-0342"
  },
  {
    "name": "진접",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "0405"
    ],
    "coordinates": [
      127.2034,
      37.7205
    ],
    "id": "station-0405"
  },
  {
    "name": "오남",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "0406"
    ],
    "coordinates": [
      127.19281,
      37.705
    ],
    "id": "station-0406"
  },
  {
    "name": "별내별가람",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "0408"
    ],
    "coordinates": [
      127.11581,
      37.66778
    ],
    "id": "station-0408"
  },
  {
    "name": "불암산",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "0409"
    ],
    "coordinates": [
      127.079066,
      37.670272
    ],
    "id": "station-0409"
  },
  {
    "name": "상계",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "0410"
    ],
    "coordinates": [
      127.073572,
      37.660878
    ],
    "id": "station-0410"
  },
  {
    "name": "노원",
    "lines": [
      "4호선",
      "7호선"
    ],
    "sourceIds": [
      "0411",
      "2715"
    ],
    "coordinates": [
      127.060462,
      37.654836
    ],
    "id": "station-0411"
  },
  {
    "name": "창동",
    "lines": [
      "1호선",
      "4호선"
    ],
    "sourceIds": [
      "0412"
    ],
    "coordinates": [
      127.047274,
      37.653088
    ],
    "id": "station-0412"
  },
  {
    "name": "쌍문",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "0413"
    ],
    "coordinates": [
      127.034709,
      37.648627
    ],
    "id": "station-0413"
  },
  {
    "name": "수유",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "0414"
    ],
    "coordinates": [
      127.025732,
      37.638052
    ],
    "id": "station-0414"
  },
  {
    "name": "미아",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "0415"
    ],
    "coordinates": [
      127.025983,
      37.62667
    ],
    "id": "station-0415"
  },
  {
    "name": "미아사거리",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "0416"
    ],
    "coordinates": [
      127.030053,
      37.613292
    ],
    "id": "station-0416"
  },
  {
    "name": "길음",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "0417"
    ],
    "coordinates": [
      127.025053,
      37.603407
    ],
    "id": "station-0417"
  },
  {
    "name": "성신여대입구",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "0418"
    ],
    "coordinates": [
      127.016441,
      37.592612
    ],
    "id": "station-0418"
  },
  {
    "name": "한성대입구",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "0419"
    ],
    "coordinates": [
      127.006221,
      37.588458
    ],
    "id": "station-0419"
  },
  {
    "name": "혜화",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "0420"
    ],
    "coordinates": [
      127.001844,
      37.582336
    ],
    "id": "station-0420"
  },
  {
    "name": "명동",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "0424"
    ],
    "coordinates": [
      126.986325,
      37.560989
    ],
    "id": "station-0424"
  },
  {
    "name": "회현",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "0425"
    ],
    "coordinates": [
      126.978246,
      37.558514
    ],
    "id": "station-0425"
  },
  {
    "name": "숙대입구",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "0427"
    ],
    "coordinates": [
      126.972106,
      37.54456
    ],
    "id": "station-0427"
  },
  {
    "name": "삼각지",
    "lines": [
      "4호선",
      "6호선"
    ],
    "sourceIds": [
      "0428",
      "2629"
    ],
    "coordinates": [
      126.974032,
      37.535534
    ],
    "id": "station-0428"
  },
  {
    "name": "신용산",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "0429"
    ],
    "coordinates": [
      126.967894,
      37.52917
    ],
    "id": "station-0429"
  },
  {
    "name": "이촌",
    "lines": [
      "4호선",
      "경의중앙선"
    ],
    "sourceIds": [
      "0430",
      "1008"
    ],
    "coordinates": [
      126.974733,
      37.522295
    ],
    "id": "station-0430"
  },
  {
    "name": "동작",
    "lines": [
      "4호선",
      "9호선"
    ],
    "sourceIds": [
      "0431",
      "4120"
    ],
    "coordinates": [
      126.978153,
      37.502878
    ],
    "id": "station-0431"
  },
  {
    "name": "총신대입구(이수)",
    "lines": [
      "4호선",
      "7호선"
    ],
    "sourceIds": [
      "0432",
      "2738"
    ],
    "coordinates": [
      126.981605,
      37.485196
    ],
    "id": "station-0432"
  },
  {
    "name": "남태령",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "0434"
    ],
    "coordinates": [
      126.989134,
      37.463873
    ],
    "id": "station-0434"
  },
  {
    "name": "남영",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1002"
    ],
    "coordinates": [
      126.9713,
      37.541021
    ],
    "id": "station-1002"
  },
  {
    "name": "용산",
    "lines": [
      "1호선",
      "경의중앙선"
    ],
    "sourceIds": [
      "1003"
    ],
    "coordinates": [
      126.964561,
      37.529849
    ],
    "id": "station-1003"
  },
  {
    "name": "노량진",
    "lines": [
      "1호선",
      "9호선"
    ],
    "sourceIds": [
      "1004",
      "4117"
    ],
    "coordinates": [
      126.941005,
      37.513534
    ],
    "id": "station-1004"
  },
  {
    "name": "대방",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1005"
    ],
    "coordinates": [
      126.926382,
      37.513342
    ],
    "id": "station-1005"
  },
  {
    "name": "영등포",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1006"
    ],
    "coordinates": [
      126.907628,
      37.515504
    ],
    "id": "station-1006"
  },
  {
    "name": "서빙고",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1009"
    ],
    "coordinates": [
      126.988537,
      37.519594
    ],
    "id": "station-1009"
  },
  {
    "name": "한남",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1010"
    ],
    "coordinates": [
      127.009169,
      37.52943
    ],
    "id": "station-1010"
  },
  {
    "name": "응봉",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1012"
    ],
    "coordinates": [
      127.034538,
      37.549946
    ],
    "id": "station-1012"
  },
  {
    "name": "회기",
    "lines": [
      "1호선",
      "경의중앙선"
    ],
    "sourceIds": [
      "1015"
    ],
    "coordinates": [
      127.057583,
      37.58946
    ],
    "id": "station-1015"
  },
  {
    "name": "외대앞",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1016"
    ],
    "coordinates": [
      127.063549,
      37.596073
    ],
    "id": "station-1016"
  },
  {
    "name": "신이문",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1017"
    ],
    "coordinates": [
      127.067325,
      37.601854
    ],
    "id": "station-1017"
  },
  {
    "name": "석계",
    "lines": [
      "1호선",
      "6호선"
    ],
    "sourceIds": [
      "1018",
      "2645"
    ],
    "coordinates": [
      127.065595,
      37.614872
    ],
    "id": "station-1018"
  },
  {
    "name": "광운대",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1019"
    ],
    "coordinates": [
      127.061835,
      37.623632
    ],
    "id": "station-1019"
  },
  {
    "name": "월계",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1020"
    ],
    "coordinates": [
      127.058831,
      37.633212
    ],
    "id": "station-1020"
  },
  {
    "name": "녹천",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1021"
    ],
    "coordinates": [
      127.051269,
      37.644799
    ],
    "id": "station-1021"
  },
  {
    "name": "신길",
    "lines": [
      "1호선",
      "5호선"
    ],
    "sourceIds": [
      "1032",
      "2526"
    ],
    "coordinates": [
      126.914839,
      37.517623
    ],
    "id": "station-1032"
  },
  {
    "name": "중랑",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1201"
    ],
    "coordinates": [
      127.076116,
      37.594917
    ],
    "id": "station-1201"
  },
  {
    "name": "상봉",
    "lines": [
      "7호선",
      "경의중앙선"
    ],
    "sourceIds": [
      "1202",
      "2722"
    ],
    "coordinates": [
      127.085716,
      37.595577
    ],
    "id": "station-1202"
  },
  {
    "name": "망우",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1203"
    ],
    "coordinates": [
      127.091909,
      37.59955
    ],
    "id": "station-1203"
  },
  {
    "name": "양원",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1204"
    ],
    "coordinates": [
      127.107906,
      37.606596
    ],
    "id": "station-1204"
  },
  {
    "name": "구리",
    "lines": [
      "8호선",
      "경의중앙선"
    ],
    "sourceIds": [
      "1205",
      "2808"
    ],
    "coordinates": [
      127.143869,
      37.603392
    ],
    "id": "station-1205"
  },
  {
    "name": "도농",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1206"
    ],
    "coordinates": [
      127.161153,
      37.608806
    ],
    "id": "station-1206"
  },
  {
    "name": "양정",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1207"
    ],
    "coordinates": [
      127.19364,
      37.60533
    ],
    "id": "station-1207"
  },
  {
    "name": "덕소",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1208"
    ],
    "coordinates": [
      127.208832,
      37.586781
    ],
    "id": "station-1208"
  },
  {
    "name": "도심",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1209"
    ],
    "coordinates": [
      127.222672,
      37.579622
    ],
    "id": "station-1209"
  },
  {
    "name": "팔당",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1210"
    ],
    "coordinates": [
      127.243939,
      37.547371
    ],
    "id": "station-1210"
  },
  {
    "name": "운길산",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1211"
    ],
    "coordinates": [
      127.310115,
      37.554669
    ],
    "id": "station-1211"
  },
  {
    "name": "양수",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1212"
    ],
    "coordinates": [
      127.329098,
      37.545981
    ],
    "id": "station-1212"
  },
  {
    "name": "신원",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1213"
    ],
    "coordinates": [
      127.372921,
      37.525545
    ],
    "id": "station-1213"
  },
  {
    "name": "국수",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1214"
    ],
    "coordinates": [
      127.399367,
      37.516169
    ],
    "id": "station-1214"
  },
  {
    "name": "아신",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1215"
    ],
    "coordinates": [
      127.443173,
      37.51382
    ],
    "id": "station-1215"
  },
  {
    "name": "오빈",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1216"
    ],
    "coordinates": [
      127.473868,
      37.506062
    ],
    "id": "station-1216"
  },
  {
    "name": "양평",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1217"
    ],
    "coordinates": [
      127.491837,
      37.492773
    ],
    "id": "station-1217"
  },
  {
    "name": "원덕",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1218"
    ],
    "coordinates": [
      127.547076,
      37.468672
    ],
    "id": "station-1218"
  },
  {
    "name": "용문",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1219"
    ],
    "coordinates": [
      127.594647,
      37.48223
    ],
    "id": "station-1219"
  },
  {
    "name": "지평",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1220"
    ],
    "coordinates": [
      127.629874,
      37.476393
    ],
    "id": "station-1220"
  },
  {
    "name": "신촌",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1252"
    ],
    "coordinates": [
      126.942597,
      37.559733
    ],
    "id": "station-1252"
  },
  {
    "name": "효창공원앞",
    "lines": [
      "6호선",
      "경의중앙선"
    ],
    "sourceIds": [
      "1261",
      "2628"
    ],
    "coordinates": [
      126.96221,
      37.538579
    ],
    "id": "station-1261"
  },
  {
    "name": "공덕",
    "lines": [
      "5호선",
      "6호선",
      "경의중앙선"
    ],
    "sourceIds": [
      "1262",
      "2530",
      "2627"
    ],
    "coordinates": [
      126.951678,
      37.543555
    ],
    "id": "station-1262"
  },
  {
    "name": "서강대",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1263"
    ],
    "coordinates": [
      126.935711,
      37.551881
    ],
    "id": "station-1263"
  },
  {
    "name": "가좌",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1265"
    ],
    "coordinates": [
      126.915487,
      37.568491
    ],
    "id": "station-1265"
  },
  {
    "name": "디지털미디어시티",
    "lines": [
      "6호선",
      "경의중앙선"
    ],
    "sourceIds": [
      "1266",
      "2619"
    ],
    "coordinates": [
      126.900453,
      37.577475
    ],
    "id": "station-1266"
  },
  {
    "name": "수색",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1267"
    ],
    "coordinates": [
      126.895611,
      37.580842
    ],
    "id": "station-1267"
  },
  {
    "name": "한국항공대",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1268"
    ],
    "coordinates": [
      126.868387,
      37.602888
    ],
    "id": "station-1268"
  },
  {
    "name": "강매",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1269"
    ],
    "coordinates": [
      126.843223,
      37.612314
    ],
    "id": "station-1269"
  },
  {
    "name": "행신",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1270"
    ],
    "coordinates": [
      126.834146,
      37.612102
    ],
    "id": "station-1270"
  },
  {
    "name": "능곡",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1271"
    ],
    "coordinates": [
      126.820783,
      37.618808
    ],
    "id": "station-1271"
  },
  {
    "name": "곡산",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1272"
    ],
    "coordinates": [
      126.801762,
      37.645676
    ],
    "id": "station-1272"
  },
  {
    "name": "백마",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1273"
    ],
    "coordinates": [
      126.794461,
      37.658239
    ],
    "id": "station-1273"
  },
  {
    "name": "풍산",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1274"
    ],
    "coordinates": [
      126.786243,
      37.672346
    ],
    "id": "station-1274"
  },
  {
    "name": "일산",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1275"
    ],
    "coordinates": [
      126.769846,
      37.682077
    ],
    "id": "station-1275"
  },
  {
    "name": "탄현",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1276"
    ],
    "coordinates": [
      126.761086,
      37.694023
    ],
    "id": "station-1276"
  },
  {
    "name": "야당",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1277"
    ],
    "coordinates": [
      126.761356,
      37.712327
    ],
    "id": "station-1277"
  },
  {
    "name": "운정",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1278"
    ],
    "coordinates": [
      126.767257,
      37.725826
    ],
    "id": "station-1278"
  },
  {
    "name": "금릉",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1279"
    ],
    "coordinates": [
      126.765347,
      37.751322
    ],
    "id": "station-1279"
  },
  {
    "name": "금촌",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1280"
    ],
    "coordinates": [
      126.774644,
      37.766217
    ],
    "id": "station-1280"
  },
  {
    "name": "월롱",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1282"
    ],
    "coordinates": [
      126.792587,
      37.796188
    ],
    "id": "station-1282"
  },
  {
    "name": "파주",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1283"
    ],
    "coordinates": [
      126.792783,
      37.815298
    ],
    "id": "station-1283"
  },
  {
    "name": "문산",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1284"
    ],
    "coordinates": [
      126.788047,
      37.854619
    ],
    "id": "station-1284"
  },
  {
    "name": "임진강",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1285"
    ],
    "coordinates": [
      126.746765,
      37.888421
    ],
    "note": "운행 횟수가 적은 구간 · 시간표 확인 필요",
    "id": "station-1285"
  },
  {
    "name": "운천",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "1286"
    ],
    "coordinates": [
      126.769999,
      37.879942
    ],
    "note": "운행 횟수가 적은 구간 · 시간표 확인 필요",
    "id": "station-1286"
  },
  {
    "name": "봉명",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1401"
    ],
    "coordinates": [
      127.135763,
      36.801215
    ],
    "id": "station-1401"
  },
  {
    "name": "쌍용",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1402"
    ],
    "coordinates": [
      127.1214,
      36.793759
    ],
    "id": "station-1402"
  },
  {
    "name": "아산",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1403"
    ],
    "coordinates": [
      127.104361,
      36.792053
    ],
    "id": "station-1403"
  },
  {
    "name": "탕정",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1404"
    ],
    "coordinates": [
      127.08485,
      36.78866
    ],
    "id": "station-1404"
  },
  {
    "name": "배방",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1405"
    ],
    "coordinates": [
      127.052991,
      36.777629
    ],
    "id": "station-1405"
  },
  {
    "name": "온양온천",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1407"
    ],
    "coordinates": [
      127.003249,
      36.780483
    ],
    "id": "station-1407"
  },
  {
    "name": "신창",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1408"
    ],
    "coordinates": [
      126.951108,
      36.769502
    ],
    "id": "station-1408"
  },
  {
    "name": "선바위",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "1450"
    ],
    "coordinates": [
      127.002303,
      37.451673
    ],
    "id": "station-1450"
  },
  {
    "name": "경마공원",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "1451"
    ],
    "coordinates": [
      127.007888,
      37.443885
    ],
    "id": "station-1451"
  },
  {
    "name": "대공원",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "1452"
    ],
    "coordinates": [
      127.006523,
      37.435675
    ],
    "id": "station-1452"
  },
  {
    "name": "과천",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "1453"
    ],
    "coordinates": [
      126.996568,
      37.433021
    ],
    "id": "station-1453"
  },
  {
    "name": "정부과천청사",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "1454"
    ],
    "coordinates": [
      126.98978,
      37.426513
    ],
    "id": "station-1454"
  },
  {
    "name": "인덕원",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "1455"
    ],
    "coordinates": [
      126.976715,
      37.401553
    ],
    "id": "station-1455"
  },
  {
    "name": "평촌",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "1456"
    ],
    "coordinates": [
      126.963883,
      37.394287
    ],
    "id": "station-1456"
  },
  {
    "name": "범계",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "1457"
    ],
    "coordinates": [
      126.950806,
      37.389793
    ],
    "id": "station-1457"
  },
  {
    "name": "금정",
    "lines": [
      "1호선",
      "4호선"
    ],
    "sourceIds": [
      "1458",
      "1708"
    ],
    "coordinates": [
      126.943429,
      37.372221
    ],
    "id": "station-1458"
  },
  {
    "name": "구로",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1701"
    ],
    "coordinates": [
      126.881966,
      37.503039
    ],
    "id": "station-1701"
  },
  {
    "name": "가산디지털단지",
    "lines": [
      "1호선",
      "7호선"
    ],
    "sourceIds": [
      "1702",
      "2748"
    ],
    "coordinates": [
      126.882656,
      37.480338
    ],
    "id": "station-1702"
  },
  {
    "name": "금천구청",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1703"
    ],
    "coordinates": [
      126.89398,
      37.455626
    ],
    "id": "station-1703"
  },
  {
    "name": "석수",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1704"
    ],
    "coordinates": [
      126.902295,
      37.435047
    ],
    "id": "station-1704"
  },
  {
    "name": "관악",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1705"
    ],
    "coordinates": [
      126.908706,
      37.419232
    ],
    "id": "station-1705"
  },
  {
    "name": "안양",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1706"
    ],
    "coordinates": [
      126.922874,
      37.401592
    ],
    "id": "station-1706"
  },
  {
    "name": "명학",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1707"
    ],
    "coordinates": [
      126.935433,
      37.384653
    ],
    "id": "station-1707"
  },
  {
    "name": "군포",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1709"
    ],
    "coordinates": [
      126.948462,
      37.35356
    ],
    "id": "station-1709"
  },
  {
    "name": "의왕",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1710"
    ],
    "coordinates": [
      126.948217,
      37.320852
    ],
    "id": "station-1710"
  },
  {
    "name": "성균관대",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1711"
    ],
    "coordinates": [
      126.97075,
      37.300349
    ],
    "id": "station-1711"
  },
  {
    "name": "화서",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1712"
    ],
    "coordinates": [
      126.989627,
      37.283862
    ],
    "id": "station-1712"
  },
  {
    "name": "수원",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1713"
    ],
    "coordinates": [
      126.999561,
      37.266348
    ],
    "id": "station-1713"
  },
  {
    "name": "독산",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1714"
    ],
    "coordinates": [
      126.889249,
      37.466613
    ],
    "id": "station-1714"
  },
  {
    "name": "세류",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1715"
    ],
    "coordinates": [
      127.013222,
      37.245025
    ],
    "id": "station-1715"
  },
  {
    "name": "병점",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1716"
    ],
    "coordinates": [
      127.032731,
      37.207503
    ],
    "id": "station-1716"
  },
  {
    "name": "세마",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1717"
    ],
    "coordinates": [
      127.04318,
      37.187533
    ],
    "id": "station-1717"
  },
  {
    "name": "오산대",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1718"
    ],
    "coordinates": [
      127.063197,
      37.168953
    ],
    "id": "station-1718"
  },
  {
    "name": "오산",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1719"
    ],
    "coordinates": [
      127.06672,
      37.145885
    ],
    "id": "station-1719"
  },
  {
    "name": "진위",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1720"
    ],
    "coordinates": [
      127.062278,
      37.109447
    ],
    "id": "station-1720"
  },
  {
    "name": "송탄",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1721"
    ],
    "coordinates": [
      127.054301,
      37.075696
    ],
    "id": "station-1721"
  },
  {
    "name": "서정리",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1722"
    ],
    "coordinates": [
      127.052819,
      37.056496
    ],
    "id": "station-1722"
  },
  {
    "name": "평택지제",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1723"
    ],
    "coordinates": [
      127.070444,
      37.0188
    ],
    "id": "station-1723"
  },
  {
    "name": "평택",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1724"
    ],
    "coordinates": [
      127.085159,
      36.990726
    ],
    "id": "station-1724"
  },
  {
    "name": "성환",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1725"
    ],
    "coordinates": [
      127.126964,
      36.916076
    ],
    "id": "station-1725"
  },
  {
    "name": "직산",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1726"
    ],
    "coordinates": [
      127.143904,
      36.870593
    ],
    "id": "station-1726"
  },
  {
    "name": "두정",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1727"
    ],
    "coordinates": [
      127.14896,
      36.833705
    ],
    "id": "station-1727"
  },
  {
    "name": "천안",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1728"
    ],
    "coordinates": [
      127.146826,
      36.810005
    ],
    "id": "station-1728"
  },
  {
    "name": "당정",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1729"
    ],
    "coordinates": [
      126.948345,
      37.344285
    ],
    "id": "station-1729"
  },
  {
    "name": "서동탄",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1749"
    ],
    "coordinates": [
      127.051672,
      37.195504
    ],
    "id": "station-1749"
  },
  {
    "name": "광명",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1750"
    ],
    "coordinates": [
      126.884466,
      37.416182
    ],
    "id": "station-1750"
  },
  {
    "name": "산본",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "1751"
    ],
    "coordinates": [
      126.933274,
      37.358101
    ],
    "id": "station-1751"
  },
  {
    "name": "대야미",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "1752"
    ],
    "coordinates": [
      126.917332,
      37.328467
    ],
    "id": "station-1752"
  },
  {
    "name": "반월",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "1753"
    ],
    "coordinates": [
      126.903524,
      37.312212
    ],
    "id": "station-1753"
  },
  {
    "name": "상록수",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "1754"
    ],
    "coordinates": [
      126.866489,
      37.302795
    ],
    "id": "station-1754"
  },
  {
    "name": "한대앞",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "1755"
    ],
    "coordinates": [
      126.85344,
      37.309689
    ],
    "id": "station-1755"
  },
  {
    "name": "중앙",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "1756"
    ],
    "coordinates": [
      126.838573,
      37.315941
    ],
    "id": "station-1756"
  },
  {
    "name": "고잔",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "1757"
    ],
    "coordinates": [
      126.823144,
      37.316784
    ],
    "id": "station-1757"
  },
  {
    "name": "초지",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "1758"
    ],
    "coordinates": [
      126.805913,
      37.320646
    ],
    "id": "station-1758"
  },
  {
    "name": "안산",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "1759"
    ],
    "coordinates": [
      126.788532,
      37.327082
    ],
    "id": "station-1759"
  },
  {
    "name": "신길온천",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "1760"
    ],
    "coordinates": [
      126.765844,
      37.338212
    ],
    "id": "station-1760"
  },
  {
    "name": "정왕",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "1761"
    ],
    "coordinates": [
      126.742989,
      37.351735
    ],
    "id": "station-1761"
  },
  {
    "name": "오이도",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "1762"
    ],
    "coordinates": [
      126.738714,
      37.362357
    ],
    "id": "station-1762"
  },
  {
    "name": "수리산",
    "lines": [
      "4호선"
    ],
    "sourceIds": [
      "1763"
    ],
    "coordinates": [
      126.925365,
      37.349801
    ],
    "id": "station-1763"
  },
  {
    "name": "개봉",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1801"
    ],
    "coordinates": [
      126.85968,
      37.494594
    ],
    "id": "station-1801"
  },
  {
    "name": "오류동",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1802"
    ],
    "coordinates": [
      126.845365,
      37.494526
    ],
    "id": "station-1802"
  },
  {
    "name": "역곡",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1803"
    ],
    "coordinates": [
      126.811502,
      37.485178
    ],
    "id": "station-1803"
  },
  {
    "name": "부천",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1804"
    ],
    "coordinates": [
      126.782686,
      37.48405
    ],
    "id": "station-1804"
  },
  {
    "name": "송내",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1805"
    ],
    "coordinates": [
      126.753664,
      37.4876
    ],
    "id": "station-1805"
  },
  {
    "name": "부평",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1806"
    ],
    "coordinates": [
      126.724506,
      37.489445
    ],
    "id": "station-1806"
  },
  {
    "name": "백운",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1807"
    ],
    "coordinates": [
      126.707704,
      37.483664
    ],
    "id": "station-1807"
  },
  {
    "name": "동암",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1808"
    ],
    "coordinates": [
      126.702896,
      37.471408
    ],
    "id": "station-1808"
  },
  {
    "name": "주안",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1809"
    ],
    "coordinates": [
      126.679742,
      37.465047
    ],
    "id": "station-1809"
  },
  {
    "name": "제물포",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1810"
    ],
    "coordinates": [
      126.656666,
      37.466769
    ],
    "id": "station-1810"
  },
  {
    "name": "동인천",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1811"
    ],
    "coordinates": [
      126.632802,
      37.475276
    ],
    "id": "station-1811"
  },
  {
    "name": "인천",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1812"
    ],
    "coordinates": [
      126.616801,
      37.476079
    ],
    "id": "station-1812"
  },
  {
    "name": "구일",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1813"
    ],
    "coordinates": [
      126.870793,
      37.496756
    ],
    "id": "station-1813"
  },
  {
    "name": "소사",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1814"
    ],
    "coordinates": [
      126.79544,
      37.482753
    ],
    "id": "station-1814"
  },
  {
    "name": "부개",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1815"
    ],
    "coordinates": [
      126.74109,
      37.488418
    ],
    "id": "station-1815"
  },
  {
    "name": "간석",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1816"
    ],
    "coordinates": [
      126.694181,
      37.464737
    ],
    "id": "station-1816"
  },
  {
    "name": "도원",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1817"
    ],
    "coordinates": [
      126.642706,
      37.468446
    ],
    "id": "station-1817"
  },
  {
    "name": "온수",
    "lines": [
      "1호선",
      "7호선"
    ],
    "sourceIds": [
      "1821",
      "2752"
    ],
    "coordinates": [
      126.823023,
      37.492092
    ],
    "id": "station-1821"
  },
  {
    "name": "중동",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1822"
    ],
    "coordinates": [
      126.764843,
      37.486562
    ],
    "id": "station-1822"
  },
  {
    "name": "도화",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1823"
    ],
    "coordinates": [
      126.668672,
      37.46607
    ],
    "id": "station-1823"
  },
  {
    "name": "방학",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1901"
    ],
    "coordinates": [
      127.044273,
      37.667503
    ],
    "id": "station-1901"
  },
  {
    "name": "도봉",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1902"
    ],
    "coordinates": [
      127.045595,
      37.679563
    ],
    "id": "station-1902"
  },
  {
    "name": "도봉산",
    "lines": [
      "1호선",
      "7호선"
    ],
    "sourceIds": [
      "1903",
      "2712"
    ],
    "coordinates": [
      127.046509,
      37.689241
    ],
    "id": "station-1903"
  },
  {
    "name": "망월사",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1904"
    ],
    "coordinates": [
      127.047455,
      37.709914
    ],
    "id": "station-1904"
  },
  {
    "name": "회룡",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1905"
    ],
    "coordinates": [
      127.04736,
      37.724416
    ],
    "id": "station-1905"
  },
  {
    "name": "의정부",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1906"
    ],
    "coordinates": [
      127.045958,
      37.738415
    ],
    "id": "station-1906"
  },
  {
    "name": "가능",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1907"
    ],
    "coordinates": [
      127.044213,
      37.748577
    ],
    "id": "station-1907"
  },
  {
    "name": "녹양",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1908"
    ],
    "coordinates": [
      127.042292,
      37.75938
    ],
    "id": "station-1908"
  },
  {
    "name": "양주",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1909"
    ],
    "coordinates": [
      127.044708,
      37.774381
    ],
    "id": "station-1909"
  },
  {
    "name": "덕계",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1910"
    ],
    "coordinates": [
      127.056486,
      37.818486
    ],
    "id": "station-1910"
  },
  {
    "name": "덕정",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1911"
    ],
    "coordinates": [
      127.061277,
      37.843188
    ],
    "id": "station-1911"
  },
  {
    "name": "지행",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1912"
    ],
    "coordinates": [
      127.055716,
      37.892334
    ],
    "id": "station-1912"
  },
  {
    "name": "동두천중앙",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1913"
    ],
    "coordinates": [
      127.056482,
      37.901885
    ],
    "id": "station-1913"
  },
  {
    "name": "보산",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1914"
    ],
    "coordinates": [
      127.057277,
      37.913702
    ],
    "id": "station-1914"
  },
  {
    "name": "동두천",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1915"
    ],
    "coordinates": [
      127.05479,
      37.927878
    ],
    "id": "station-1915"
  },
  {
    "name": "소요산",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1916"
    ],
    "coordinates": [
      127.061034,
      37.9481
    ],
    "id": "station-1916"
  },
  {
    "name": "청산",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1917"
    ],
    "coordinates": [
      127.06912,
      37.98172
    ],
    "id": "station-1917"
  },
  {
    "name": "전곡",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1918"
    ],
    "coordinates": [
      127.0718,
      38.02458
    ],
    "id": "station-1918"
  },
  {
    "name": "연천",
    "lines": [
      "1호선"
    ],
    "sourceIds": [
      "1919"
    ],
    "coordinates": [
      127.07372,
      38.10073
    ],
    "id": "station-1919"
  },
  {
    "name": "원흥",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "1948"
    ],
    "coordinates": [
      126.872642,
      37.650658
    ],
    "id": "station-1948"
  },
  {
    "name": "삼송",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "1950"
    ],
    "coordinates": [
      126.895558,
      37.653083
    ],
    "id": "station-1950"
  },
  {
    "name": "원당",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "1951"
    ],
    "coordinates": [
      126.843041,
      37.653324
    ],
    "id": "station-1951"
  },
  {
    "name": "화정",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "1952"
    ],
    "coordinates": [
      126.83265,
      37.634592
    ],
    "id": "station-1952"
  },
  {
    "name": "대곡",
    "lines": [
      "3호선",
      "경의중앙선"
    ],
    "sourceIds": [
      "1953"
    ],
    "coordinates": [
      126.811024,
      37.631626
    ],
    "id": "station-1953"
  },
  {
    "name": "백석",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "1954"
    ],
    "coordinates": [
      126.78787,
      37.643114
    ],
    "id": "station-1954"
  },
  {
    "name": "마두",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "1955"
    ],
    "coordinates": [
      126.77762,
      37.652206
    ],
    "id": "station-1955"
  },
  {
    "name": "정발산",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "1956"
    ],
    "coordinates": [
      126.773359,
      37.659477
    ],
    "id": "station-1956"
  },
  {
    "name": "주엽",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "1957"
    ],
    "coordinates": [
      126.761334,
      37.670072
    ],
    "id": "station-1957"
  },
  {
    "name": "대화",
    "lines": [
      "3호선"
    ],
    "sourceIds": [
      "1958"
    ],
    "coordinates": [
      126.747569,
      37.676087
    ],
    "id": "station-1958"
  },
  {
    "name": "방화",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2511"
    ],
    "coordinates": [
      126.812741,
      37.577446
    ],
    "id": "station-2511"
  },
  {
    "name": "개화산",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2512"
    ],
    "coordinates": [
      126.806171,
      37.572399
    ],
    "id": "station-2512"
  },
  {
    "name": "김포공항",
    "lines": [
      "5호선",
      "9호선"
    ],
    "sourceIds": [
      "2513",
      "4102"
    ],
    "coordinates": [
      126.802152,
      37.561916
    ],
    "id": "station-2513"
  },
  {
    "name": "송정",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2514"
    ],
    "coordinates": [
      126.811973,
      37.561184
    ],
    "id": "station-2514"
  },
  {
    "name": "마곡",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2515"
    ],
    "coordinates": [
      126.825448,
      37.560183
    ],
    "id": "station-2515"
  },
  {
    "name": "발산",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2516"
    ],
    "coordinates": [
      126.837668,
      37.558598
    ],
    "id": "station-2516"
  },
  {
    "name": "우장산",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2517"
    ],
    "coordinates": [
      126.836318,
      37.548768
    ],
    "id": "station-2517"
  },
  {
    "name": "화곡",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2518"
    ],
    "coordinates": [
      126.840461,
      37.541513
    ],
    "id": "station-2518"
  },
  {
    "name": "까치산",
    "lines": [
      "2호선",
      "5호선"
    ],
    "sourceIds": [
      "2519"
    ],
    "coordinates": [
      126.846683,
      37.531768
    ],
    "id": "station-2519"
  },
  {
    "name": "신정",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2520"
    ],
    "coordinates": [
      126.856191,
      37.524997
    ],
    "id": "station-2520"
  },
  {
    "name": "목동",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2521"
    ],
    "coordinates": [
      126.864931,
      37.526065
    ],
    "id": "station-2521"
  },
  {
    "name": "오목교",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2522"
    ],
    "coordinates": [
      126.875181,
      37.524496
    ],
    "id": "station-2522"
  },
  {
    "name": "양평",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2523"
    ],
    "coordinates": [
      126.886129,
      37.525569
    ],
    "id": "station-2523"
  },
  {
    "name": "영등포시장",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2525"
    ],
    "coordinates": [
      126.905139,
      37.522669
    ],
    "id": "station-2525"
  },
  {
    "name": "여의도",
    "lines": [
      "5호선",
      "9호선"
    ],
    "sourceIds": [
      "2527",
      "4115"
    ],
    "coordinates": [
      126.92403,
      37.52176
    ],
    "id": "station-2527"
  },
  {
    "name": "여의나루",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2528"
    ],
    "coordinates": [
      126.932901,
      37.527098
    ],
    "id": "station-2528"
  },
  {
    "name": "마포",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2529"
    ],
    "coordinates": [
      126.945932,
      37.539574
    ],
    "id": "station-2529"
  },
  {
    "name": "애오개",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2531"
    ],
    "coordinates": [
      126.95682,
      37.553736
    ],
    "id": "station-2531"
  },
  {
    "name": "서대문",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2533"
    ],
    "coordinates": [
      126.966641,
      37.565773
    ],
    "id": "station-2533"
  },
  {
    "name": "광화문",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2534"
    ],
    "coordinates": [
      126.97717,
      37.571525
    ],
    "id": "station-2534"
  },
  {
    "name": "청구",
    "lines": [
      "5호선",
      "6호선"
    ],
    "sourceIds": [
      "2538",
      "2635"
    ],
    "coordinates": [
      127.013639,
      37.560276
    ],
    "id": "station-2538"
  },
  {
    "name": "신금호",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2539"
    ],
    "coordinates": [
      127.020331,
      37.554548
    ],
    "id": "station-2539"
  },
  {
    "name": "행당",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2540"
    ],
    "coordinates": [
      127.029476,
      37.557322
    ],
    "id": "station-2540"
  },
  {
    "name": "마장",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2542"
    ],
    "coordinates": [
      127.042973,
      37.5661
    ],
    "id": "station-2542"
  },
  {
    "name": "답십리",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2543"
    ],
    "coordinates": [
      127.052704,
      37.566747
    ],
    "id": "station-2543"
  },
  {
    "name": "장한평",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2544"
    ],
    "coordinates": [
      127.064623,
      37.56144
    ],
    "id": "station-2544"
  },
  {
    "name": "군자",
    "lines": [
      "5호선",
      "7호선"
    ],
    "sourceIds": [
      "2545",
      "2727"
    ],
    "coordinates": [
      127.079577,
      37.557088
    ],
    "id": "station-2545"
  },
  {
    "name": "아차산",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2546"
    ],
    "coordinates": [
      127.089761,
      37.551691
    ],
    "id": "station-2546"
  },
  {
    "name": "광나루",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2547"
    ],
    "coordinates": [
      127.10357,
      37.545303
    ],
    "id": "station-2547"
  },
  {
    "name": "천호",
    "lines": [
      "5호선",
      "8호선"
    ],
    "sourceIds": [
      "2548",
      "2812"
    ],
    "coordinates": [
      127.123254,
      37.538113
    ],
    "id": "station-2548"
  },
  {
    "name": "강동",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2549"
    ],
    "coordinates": [
      127.132481,
      37.535804
    ],
    "id": "station-2549"
  },
  {
    "name": "길동",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2550"
    ],
    "coordinates": [
      127.140004,
      37.537801
    ],
    "id": "station-2550"
  },
  {
    "name": "굽은다리",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2551"
    ],
    "coordinates": [
      127.142853,
      37.545477
    ],
    "id": "station-2551"
  },
  {
    "name": "명일",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2552"
    ],
    "coordinates": [
      127.143999,
      37.55137
    ],
    "id": "station-2552"
  },
  {
    "name": "고덕",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2553"
    ],
    "coordinates": [
      127.154151,
      37.555004
    ],
    "id": "station-2553"
  },
  {
    "name": "상일동",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2554"
    ],
    "coordinates": [
      127.166417,
      37.556712
    ],
    "id": "station-2554"
  },
  {
    "name": "둔촌동",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2555"
    ],
    "coordinates": [
      127.136248,
      37.527788
    ],
    "id": "station-2555"
  },
  {
    "name": "올림픽공원",
    "lines": [
      "5호선",
      "9호선"
    ],
    "sourceIds": [
      "2556",
      "4136"
    ],
    "coordinates": [
      127.130923,
      37.516201
    ],
    "id": "station-2556"
  },
  {
    "name": "방이",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2557"
    ],
    "coordinates": [
      127.126133,
      37.508857
    ],
    "id": "station-2557"
  },
  {
    "name": "개롱",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2559"
    ],
    "coordinates": [
      127.13482,
      37.498079
    ],
    "id": "station-2559"
  },
  {
    "name": "거여",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2560"
    ],
    "coordinates": [
      127.14415,
      37.493105
    ],
    "id": "station-2560"
  },
  {
    "name": "마천",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2561"
    ],
    "coordinates": [
      127.152781,
      37.49499
    ],
    "id": "station-2561"
  },
  {
    "name": "강일",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2562"
    ],
    "coordinates": [
      127.17593,
      37.55749
    ],
    "id": "station-2562"
  },
  {
    "name": "미사",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2563"
    ],
    "coordinates": [
      127.193877,
      37.560927
    ],
    "id": "station-2563"
  },
  {
    "name": "하남풍산",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2564"
    ],
    "coordinates": [
      127.203864,
      37.552034
    ],
    "id": "station-2564"
  },
  {
    "name": "하남시청",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2565"
    ],
    "coordinates": [
      127.20612,
      37.54205
    ],
    "id": "station-2565"
  },
  {
    "name": "하남검단산",
    "lines": [
      "5호선"
    ],
    "sourceIds": [
      "2566"
    ],
    "coordinates": [
      127.22345,
      37.53972
    ],
    "id": "station-2566"
  },
  {
    "name": "응암",
    "lines": [
      "6호선"
    ],
    "sourceIds": [
      "2611"
    ],
    "coordinates": [
      126.915577,
      37.598605
    ],
    "id": "station-2611"
  },
  {
    "name": "역촌",
    "lines": [
      "6호선"
    ],
    "sourceIds": [
      "2612"
    ],
    "coordinates": [
      126.922744,
      37.606021
    ],
    "id": "station-2612"
  },
  {
    "name": "독바위",
    "lines": [
      "6호선"
    ],
    "sourceIds": [
      "2614"
    ],
    "coordinates": [
      126.933031,
      37.618456
    ],
    "id": "station-2614"
  },
  {
    "name": "구산",
    "lines": [
      "6호선"
    ],
    "sourceIds": [
      "2616"
    ],
    "coordinates": [
      126.91727,
      37.611377
    ],
    "id": "station-2616"
  },
  {
    "name": "새절",
    "lines": [
      "6호선"
    ],
    "sourceIds": [
      "2617"
    ],
    "coordinates": [
      126.913629,
      37.591148
    ],
    "id": "station-2617"
  },
  {
    "name": "증산",
    "lines": [
      "6호선"
    ],
    "sourceIds": [
      "2618"
    ],
    "coordinates": [
      126.909645,
      37.583876
    ],
    "id": "station-2618"
  },
  {
    "name": "월드컵경기장",
    "lines": [
      "6호선"
    ],
    "sourceIds": [
      "2620"
    ],
    "coordinates": [
      126.899298,
      37.569532
    ],
    "id": "station-2620"
  },
  {
    "name": "마포구청",
    "lines": [
      "6호선"
    ],
    "sourceIds": [
      "2621"
    ],
    "coordinates": [
      126.903343,
      37.563515
    ],
    "id": "station-2621"
  },
  {
    "name": "망원",
    "lines": [
      "6호선"
    ],
    "sourceIds": [
      "2622"
    ],
    "coordinates": [
      126.910052,
      37.556094
    ],
    "id": "station-2622"
  },
  {
    "name": "상수",
    "lines": [
      "6호선"
    ],
    "sourceIds": [
      "2624"
    ],
    "coordinates": [
      126.922852,
      37.547716
    ],
    "id": "station-2624"
  },
  {
    "name": "광흥창",
    "lines": [
      "6호선"
    ],
    "sourceIds": [
      "2625"
    ],
    "coordinates": [
      126.931993,
      37.547456
    ],
    "id": "station-2625"
  },
  {
    "name": "대흥",
    "lines": [
      "6호선"
    ],
    "sourceIds": [
      "2626"
    ],
    "coordinates": [
      126.942069,
      37.547771
    ],
    "id": "station-2626"
  },
  {
    "name": "녹사평",
    "lines": [
      "6호선"
    ],
    "sourceIds": [
      "2630"
    ],
    "coordinates": [
      126.986695,
      37.534675
    ],
    "id": "station-2630"
  },
  {
    "name": "이태원",
    "lines": [
      "6호선"
    ],
    "sourceIds": [
      "2631"
    ],
    "coordinates": [
      126.994302,
      37.534488
    ],
    "id": "station-2631"
  },
  {
    "name": "한강진",
    "lines": [
      "6호선"
    ],
    "sourceIds": [
      "2632"
    ],
    "coordinates": [
      127.001725,
      37.539631
    ],
    "id": "station-2632"
  },
  {
    "name": "버티고개",
    "lines": [
      "6호선"
    ],
    "sourceIds": [
      "2633"
    ],
    "coordinates": [
      127.007055,
      37.548013
    ],
    "id": "station-2633"
  },
  {
    "name": "창신",
    "lines": [
      "6호선"
    ],
    "sourceIds": [
      "2638"
    ],
    "coordinates": [
      127.015241,
      37.579661
    ],
    "id": "station-2638"
  },
  {
    "name": "보문",
    "lines": [
      "6호선"
    ],
    "sourceIds": [
      "2639"
    ],
    "coordinates": [
      127.019351,
      37.585274
    ],
    "id": "station-2639"
  },
  {
    "name": "안암",
    "lines": [
      "6호선"
    ],
    "sourceIds": [
      "2640"
    ],
    "coordinates": [
      127.029005,
      37.586272
    ],
    "id": "station-2640"
  },
  {
    "name": "고려대",
    "lines": [
      "6호선"
    ],
    "sourceIds": [
      "2641"
    ],
    "coordinates": [
      127.036296,
      37.590508
    ],
    "id": "station-2641"
  },
  {
    "name": "월곡",
    "lines": [
      "6호선"
    ],
    "sourceIds": [
      "2642"
    ],
    "coordinates": [
      127.041518,
      37.601948
    ],
    "id": "station-2642"
  },
  {
    "name": "상월곡",
    "lines": [
      "6호선"
    ],
    "sourceIds": [
      "2643"
    ],
    "coordinates": [
      127.048491,
      37.606377
    ],
    "id": "station-2643"
  },
  {
    "name": "돌곶이",
    "lines": [
      "6호선"
    ],
    "sourceIds": [
      "2644"
    ],
    "coordinates": [
      127.056431,
      37.610537
    ],
    "id": "station-2644"
  },
  {
    "name": "태릉입구",
    "lines": [
      "6호선",
      "7호선"
    ],
    "sourceIds": [
      "2646",
      "2719"
    ],
    "coordinates": [
      127.074735,
      37.617338
    ],
    "id": "station-2646"
  },
  {
    "name": "화랑대",
    "lines": [
      "6호선"
    ],
    "sourceIds": [
      "2647"
    ],
    "coordinates": [
      127.084689,
      37.620064
    ],
    "id": "station-2647"
  },
  {
    "name": "봉화산",
    "lines": [
      "6호선"
    ],
    "sourceIds": [
      "2648"
    ],
    "coordinates": [
      127.091401,
      37.617283
    ],
    "id": "station-2648"
  },
  {
    "name": "신내",
    "lines": [
      "6호선"
    ],
    "sourceIds": [
      "2649"
    ],
    "coordinates": [
      127.102231,
      37.613174
    ],
    "id": "station-2649"
  },
  {
    "name": "장암",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2711"
    ],
    "coordinates": [
      127.053196,
      37.700109
    ],
    "id": "station-2711"
  },
  {
    "name": "수락산",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2713"
    ],
    "coordinates": [
      127.055315,
      37.67785
    ],
    "id": "station-2713"
  },
  {
    "name": "마들",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2714"
    ],
    "coordinates": [
      127.057675,
      37.66494
    ],
    "id": "station-2714"
  },
  {
    "name": "중계",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2716"
    ],
    "coordinates": [
      127.064303,
      37.644583
    ],
    "id": "station-2716"
  },
  {
    "name": "하계",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2717"
    ],
    "coordinates": [
      127.06799,
      37.636352
    ],
    "id": "station-2717"
  },
  {
    "name": "공릉",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2718"
    ],
    "coordinates": [
      127.072896,
      37.625742
    ],
    "id": "station-2718"
  },
  {
    "name": "먹골",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2720"
    ],
    "coordinates": [
      127.077725,
      37.610637
    ],
    "id": "station-2720"
  },
  {
    "name": "중화",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2721"
    ],
    "coordinates": [
      127.079264,
      37.602545
    ],
    "id": "station-2721"
  },
  {
    "name": "면목",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2723"
    ],
    "coordinates": [
      127.087503,
      37.588579
    ],
    "id": "station-2723"
  },
  {
    "name": "사가정",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2724"
    ],
    "coordinates": [
      127.088478,
      37.580894
    ],
    "id": "station-2724"
  },
  {
    "name": "용마산",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2725"
    ],
    "coordinates": [
      127.086727,
      37.573647
    ],
    "id": "station-2725"
  },
  {
    "name": "중곡",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2726"
    ],
    "coordinates": [
      127.08432,
      37.565923
    ],
    "id": "station-2726"
  },
  {
    "name": "어린이대공원",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2728"
    ],
    "coordinates": [
      127.074658,
      37.548014
    ],
    "id": "station-2728"
  },
  {
    "name": "자양",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2730"
    ],
    "coordinates": [
      127.066704,
      37.53154
    ],
    "id": "station-2730"
  },
  {
    "name": "청담",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2731"
    ],
    "coordinates": [
      127.05335,
      37.519365
    ],
    "id": "station-2731"
  },
  {
    "name": "강남구청",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2732"
    ],
    "coordinates": [
      127.041255,
      37.517179
    ],
    "id": "station-2732"
  },
  {
    "name": "학동",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2733"
    ],
    "coordinates": [
      127.031656,
      37.514229
    ],
    "id": "station-2733"
  },
  {
    "name": "논현",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2734"
    ],
    "coordinates": [
      127.021415,
      37.511093
    ],
    "id": "station-2734"
  },
  {
    "name": "반포",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2735"
    ],
    "coordinates": [
      127.011727,
      37.508178
    ],
    "id": "station-2735"
  },
  {
    "name": "내방",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2737"
    ],
    "coordinates": [
      126.993513,
      37.487618
    ],
    "id": "station-2737"
  },
  {
    "name": "남성",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2739"
    ],
    "coordinates": [
      126.971251,
      37.484596
    ],
    "id": "station-2739"
  },
  {
    "name": "숭실대입구",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2740"
    ],
    "coordinates": [
      126.953822,
      37.496029
    ],
    "id": "station-2740"
  },
  {
    "name": "상도",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2741"
    ],
    "coordinates": [
      126.94791,
      37.502834
    ],
    "id": "station-2741"
  },
  {
    "name": "장승배기",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2742"
    ],
    "coordinates": [
      126.93915,
      37.504898
    ],
    "id": "station-2742"
  },
  {
    "name": "신대방삼거리",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2743"
    ],
    "coordinates": [
      126.928276,
      37.499701
    ],
    "id": "station-2743"
  },
  {
    "name": "보라매",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2744"
    ],
    "coordinates": [
      126.920428,
      37.499872
    ],
    "id": "station-2744"
  },
  {
    "name": "신풍",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2745"
    ],
    "coordinates": [
      126.90993,
      37.50008
    ],
    "id": "station-2745"
  },
  {
    "name": "남구로",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2747"
    ],
    "coordinates": [
      126.887249,
      37.486056
    ],
    "id": "station-2747"
  },
  {
    "name": "철산",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2749"
    ],
    "coordinates": [
      126.867911,
      37.47605
    ],
    "id": "station-2749"
  },
  {
    "name": "광명사거리",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2750"
    ],
    "coordinates": [
      126.854876,
      37.479252
    ],
    "id": "station-2750"
  },
  {
    "name": "천왕",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2751"
    ],
    "coordinates": [
      126.838713,
      37.486637
    ],
    "id": "station-2751"
  },
  {
    "name": "까치울",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2753",
      "3753"
    ],
    "coordinates": [
      126.810939,
      37.506207
    ],
    "id": "station-2753"
  },
  {
    "name": "부천종합운동장",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2754",
      "3754"
    ],
    "coordinates": [
      126.797337,
      37.50538
    ],
    "id": "station-2754"
  },
  {
    "name": "춘의",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2755",
      "3755"
    ],
    "coordinates": [
      126.787036,
      37.503663
    ],
    "id": "station-2755"
  },
  {
    "name": "신중동",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2756",
      "3756"
    ],
    "coordinates": [
      126.77596,
      37.503048
    ],
    "id": "station-2756"
  },
  {
    "name": "부천시청",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2757",
      "3757"
    ],
    "coordinates": [
      126.763538,
      37.504631
    ],
    "id": "station-2757"
  },
  {
    "name": "상동",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2758",
      "3758"
    ],
    "coordinates": [
      126.753083,
      37.505781
    ],
    "id": "station-2758"
  },
  {
    "name": "삼산체육관",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2759",
      "3759"
    ],
    "coordinates": [
      126.742153,
      37.506411
    ],
    "id": "station-2759"
  },
  {
    "name": "굴포천",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2760",
      "3760"
    ],
    "coordinates": [
      126.73128,
      37.506997
    ],
    "id": "station-2760"
  },
  {
    "name": "부평구청",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "2761",
      "3761"
    ],
    "coordinates": [
      126.721599,
      37.507394
    ],
    "id": "station-2761"
  },
  {
    "name": "별내",
    "lines": [
      "8호선"
    ],
    "sourceIds": [
      "2805"
    ],
    "coordinates": [
      127.1276,
      37.64232
    ],
    "id": "station-2805"
  },
  {
    "name": "다산",
    "lines": [
      "8호선"
    ],
    "sourceIds": [
      "2806"
    ],
    "coordinates": [
      127.14973,
      37.62429
    ],
    "id": "station-2806"
  },
  {
    "name": "동구릉",
    "lines": [
      "8호선"
    ],
    "sourceIds": [
      "2807"
    ],
    "coordinates": [
      127.13793,
      37.61105
    ],
    "id": "station-2807"
  },
  {
    "name": "장자호수공원",
    "lines": [
      "8호선"
    ],
    "sourceIds": [
      "2809"
    ],
    "coordinates": [
      127.13794,
      37.58738
    ],
    "id": "station-2809"
  },
  {
    "name": "암사역사공원",
    "lines": [
      "8호선"
    ],
    "sourceIds": [
      "2810"
    ],
    "coordinates": [
      127.13702,
      37.55695
    ],
    "id": "station-2810"
  },
  {
    "name": "암사",
    "lines": [
      "8호선"
    ],
    "sourceIds": [
      "2811"
    ],
    "coordinates": [
      127.127562,
      37.55021
    ],
    "id": "station-2811"
  },
  {
    "name": "강동구청",
    "lines": [
      "8호선"
    ],
    "sourceIds": [
      "2813"
    ],
    "coordinates": [
      127.120508,
      37.530341
    ],
    "id": "station-2813"
  },
  {
    "name": "몽촌토성",
    "lines": [
      "8호선"
    ],
    "sourceIds": [
      "2814"
    ],
    "coordinates": [
      127.112359,
      37.517409
    ],
    "id": "station-2814"
  },
  {
    "name": "석촌",
    "lines": [
      "8호선",
      "9호선"
    ],
    "sourceIds": [
      "2816",
      "4133"
    ],
    "coordinates": [
      127.106832,
      37.505557
    ],
    "id": "station-2816"
  },
  {
    "name": "송파",
    "lines": [
      "8호선"
    ],
    "sourceIds": [
      "2817"
    ],
    "coordinates": [
      127.112183,
      37.499703
    ],
    "id": "station-2817"
  },
  {
    "name": "문정",
    "lines": [
      "8호선"
    ],
    "sourceIds": [
      "2819"
    ],
    "coordinates": [
      127.1225,
      37.485855
    ],
    "id": "station-2819"
  },
  {
    "name": "장지",
    "lines": [
      "8호선"
    ],
    "sourceIds": [
      "2820"
    ],
    "coordinates": [
      127.126191,
      37.478703
    ],
    "id": "station-2820"
  },
  {
    "name": "복정",
    "lines": [
      "8호선"
    ],
    "sourceIds": [
      "2821"
    ],
    "coordinates": [
      127.126732,
      37.471052
    ],
    "id": "station-2821"
  },
  {
    "name": "산성",
    "lines": [
      "8호선"
    ],
    "sourceIds": [
      "2822"
    ],
    "coordinates": [
      127.149908,
      37.457122
    ],
    "id": "station-2822"
  },
  {
    "name": "남한산성입구",
    "lines": [
      "8호선"
    ],
    "sourceIds": [
      "2823"
    ],
    "coordinates": [
      127.159816,
      37.451535
    ],
    "id": "station-2823"
  },
  {
    "name": "단대오거리",
    "lines": [
      "8호선"
    ],
    "sourceIds": [
      "2824"
    ],
    "coordinates": [
      127.156866,
      37.44521
    ],
    "id": "station-2824"
  },
  {
    "name": "신흥",
    "lines": [
      "8호선"
    ],
    "sourceIds": [
      "2825"
    ],
    "coordinates": [
      127.147564,
      37.440918
    ],
    "id": "station-2825"
  },
  {
    "name": "수진",
    "lines": [
      "8호선"
    ],
    "sourceIds": [
      "2826"
    ],
    "coordinates": [
      127.140722,
      37.437428
    ],
    "id": "station-2826"
  },
  {
    "name": "모란",
    "lines": [
      "8호선"
    ],
    "sourceIds": [
      "2827"
    ],
    "coordinates": [
      127.129837,
      37.433824
    ],
    "id": "station-2827"
  },
  {
    "name": "남위례",
    "lines": [
      "8호선"
    ],
    "sourceIds": [
      "2828"
    ],
    "coordinates": [
      127.13977,
      37.4624
    ],
    "id": "station-2828"
  },
  {
    "name": "산곡",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "3762"
    ],
    "coordinates": [
      126.7035277,
      37.5086
    ],
    "id": "station-3762"
  },
  {
    "name": "석남",
    "lines": [
      "7호선"
    ],
    "sourceIds": [
      "3763"
    ],
    "coordinates": [
      126.6762813,
      37.5062285
    ],
    "id": "station-3763"
  },
  {
    "name": "개화",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4101"
    ],
    "coordinates": [
      126.798153,
      37.578608
    ],
    "id": "station-4101"
  },
  {
    "name": "공항시장",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4103"
    ],
    "coordinates": [
      126.810678,
      37.563726
    ],
    "id": "station-4103"
  },
  {
    "name": "신방화",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4104"
    ],
    "coordinates": [
      126.816601,
      37.567532
    ],
    "id": "station-4104"
  },
  {
    "name": "마곡나루",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4105"
    ],
    "coordinates": [
      126.82731,
      37.566778
    ],
    "id": "station-4105"
  },
  {
    "name": "양천향교",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4106"
    ],
    "coordinates": [
      126.841333,
      37.568381
    ],
    "id": "station-4106"
  },
  {
    "name": "가양",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4107"
    ],
    "coordinates": [
      126.854456,
      37.561391
    ],
    "id": "station-4107"
  },
  {
    "name": "증미",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4108"
    ],
    "coordinates": [
      126.861939,
      37.557402
    ],
    "id": "station-4108"
  },
  {
    "name": "등촌",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4109"
    ],
    "coordinates": [
      126.865689,
      37.550632
    ],
    "id": "station-4109"
  },
  {
    "name": "염창",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4110"
    ],
    "coordinates": [
      126.874916,
      37.546936
    ],
    "id": "station-4110"
  },
  {
    "name": "신목동",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4111"
    ],
    "coordinates": [
      126.88308,
      37.544277
    ],
    "id": "station-4111"
  },
  {
    "name": "선유도",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4112"
    ],
    "coordinates": [
      126.893525,
      37.53802
    ],
    "id": "station-4112"
  },
  {
    "name": "국회의사당",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4114"
    ],
    "coordinates": [
      126.917874,
      37.528105
    ],
    "id": "station-4114"
  },
  {
    "name": "샛강",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4116"
    ],
    "coordinates": [
      126.928422,
      37.517274
    ],
    "id": "station-4116"
  },
  {
    "name": "노들",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4118"
    ],
    "coordinates": [
      126.953222,
      37.512887
    ],
    "id": "station-4118"
  },
  {
    "name": "흑석",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4119"
    ],
    "coordinates": [
      126.963708,
      37.50877
    ],
    "id": "station-4119"
  },
  {
    "name": "구반포",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4121"
    ],
    "coordinates": [
      126.987332,
      37.501364
    ],
    "id": "station-4121"
  },
  {
    "name": "신반포",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4122"
    ],
    "coordinates": [
      126.995925,
      37.503415
    ],
    "id": "station-4122"
  },
  {
    "name": "사평",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4124"
    ],
    "coordinates": [
      127.015259,
      37.504206
    ],
    "id": "station-4124"
  },
  {
    "name": "신논현",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4125"
    ],
    "coordinates": [
      127.02506,
      37.504598
    ],
    "id": "station-4125"
  },
  {
    "name": "언주",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4126"
    ],
    "coordinates": [
      127.033868,
      37.507287
    ],
    "id": "station-4126"
  },
  {
    "name": "선정릉",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4127"
    ],
    "coordinates": [
      127.043999,
      37.510297
    ],
    "id": "station-4127"
  },
  {
    "name": "삼성중앙",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4128"
    ],
    "coordinates": [
      127.053282,
      37.513011
    ],
    "id": "station-4128"
  },
  {
    "name": "봉은사",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4129"
    ],
    "coordinates": [
      127.060245,
      37.514219
    ],
    "id": "station-4129"
  },
  {
    "name": "삼전",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4131"
    ],
    "coordinates": [
      127.088025,
      37.504738
    ],
    "id": "station-4131"
  },
  {
    "name": "석촌고분",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4132"
    ],
    "coordinates": [
      127.097033,
      37.502558
    ],
    "id": "station-4132"
  },
  {
    "name": "송파나루",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4134"
    ],
    "coordinates": [
      127.112216,
      37.510372
    ],
    "id": "station-4134"
  },
  {
    "name": "한성백제",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4135"
    ],
    "coordinates": [
      127.116503,
      37.516404
    ],
    "id": "station-4135"
  },
  {
    "name": "둔촌오륜",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4137"
    ],
    "coordinates": [
      127.137989,
      37.519683
    ],
    "id": "station-4137"
  },
  {
    "name": "중앙보훈병원",
    "lines": [
      "9호선"
    ],
    "sourceIds": [
      "4138"
    ],
    "coordinates": [
      127.148739,
      37.529191
    ],
    "id": "station-4138"
  },
  {
    "name": "도라산",
    "lines": [
      "경의중앙선"
    ],
    "sourceIds": [
      "korail-dorasan"
    ],
    "note": "민통선 구간 · 사전 예약과 운행일 확인 필요",
    "id": "station-korail-dorasan"
  }
].map(station => Object.freeze({...station, lines:Object.freeze(station.lines)})));
