import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const {PGlite}=await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
const db=new PGlite();
const owner='00000000-0000-4000-8000-000000000001',other='00000000-0000-4000-8000-000000000002';
const a='10000000-0000-4000-8000-000000000001',b='10000000-0000-4000-8000-000000000002';
try {
  await db.exec(`create role anon;create role authenticated;create schema auth;
    create table auth.users(id uuid primary key);
    create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
    grant usage on schema auth to authenticated;
    insert into auth.users values('${owner}'),('${other}');
    create schema test;create table test.clock(value timestamptz);
    insert into test.clock values('2026-09-30T14:00:00Z');
    create function test.now() returns timestamptz language sql as $$select value from test.clock$$;`);
  const migration=async name=>(await readFile(new URL(`../supabase/${name}.sql`,import.meta.url),'utf8')).replaceAll('clock_timestamp()','test.now()');
  await db.exec(await migration('daily'));await db.exec(await migration('daily-midnight'));
  const notes=await migration('daily-notes');
  const signIn=async id=>db.exec(`reset role;set role authenticated;set request.jwt.claim.sub='${id}';`);
  const state=async()=>(await db.query('select public.daily_plan_state() as data')).rows[0].data;
  const update=async(s,action,tasks=null,id=null,done=null)=>(await db.query('select public.daily_plan_update($1::date,$2::bigint,$3::text,$4::jsonb,$5::uuid,$6::boolean) as data',[s.day,s.revision,action,tasks&&JSON.stringify(tasks),id,done])).rows[0].data;
  await signIn(owner);
  let s=await update(await state(),'save',[{id:a,title:'자료 읽기'},{id:b,title:'운동'}]);
  s=await update(s,'check',null,a,true);
  const timestamp=(await db.query('select completed_at from daily_tasks where id=$1',[a])).rows[0].completed_at;
  await db.exec('reset role;');await db.exec(notes);await signIn(owner);
  s=await state();assert.equal(s.tasks[0].note,'');assert.equal(s.tasks[0].completed,true,'migration preserves existing checks');
  s=await update(s,'save',[{id:a,title:'자료 읽기',note:'2장까지 읽기\n핵심 내용 정리'},{id:b,title:'운동',note:''}]);
  assert.equal(s.tasks[0].completed,true);
  assert.deepEqual((await db.query('select completed_at from daily_tasks where id=$1',[a])).rows[0].completed_at,timestamp,'notes-only edits preserve completion timestamp');
  assert.equal((await state()).tasks[0].note,'2장까지 읽기\n핵심 내용 정리');
  s=await update(s,'check',null,b,true);assert.equal(s.tasks[1].completed,true,'blank note permits completion');
  s=await update(s,'check',null,a,false);s=await update(s,'check',null,a,true);
  s=await update(s,'save',[{id:a,title:'자료 읽기'},{id:b,title:'운동'}]);
  assert.equal(s.tasks[0].note,'2장까지 읽기\n핵심 내용 정리','old clients cannot erase notes by omitting them');
  const stale=s;
  s=await update(s,'save',[{id:a,title:'자료 읽기',note:'수정한 메모'},{id:b,title:'운동'}]);
  await assert.rejects(update(stale,'save',[{id:a,title:'자료 읽기',note:'덮어쓰기'}]),/PLAN_CHANGED/);
  for(const note of ['가'.repeat(2001),{},123,false,[]])
    await assert.rejects(update(s,'save',[{id:a,title:'자료 읽기',note},{id:b,title:'운동'}]),/INVALID_NOTE/);
  assert.equal((await state()).tasks[0].note,'수정한 메모','invalid writes roll back');
  s=await update(s,'save',[{id:a,title:'자료 읽기',note:'가'.repeat(2000)},{id:b,title:'운동',note:null}]);
  assert.equal(s.tasks[0].note.length,2000);assert.equal(s.tasks[1].note,'');
  s=await update(s,'save',[{id:a,title:'자료 읽기',note:''},{id:b,title:'운동'}]);
  assert.equal(s.tasks[0].note,'');assert.equal(s.tasks[0].completed,true,'clearing a note preserves completion');
  await assert.rejects(db.query('update daily_tasks set note=$1 where id=$2',['bypass',a]),e=>e.code==='42501');
  await signIn(other);assert.equal((await db.query('select note from daily_tasks')).rows.length,0);
  let t=await update(await state(),'save',[{id:a,title:'Other',note:'Private'}]);
  await assert.rejects(update({...t,day:'2026-09-29'},'save',[{id:a,title:'Other',note:'rewrite'}]),/DAY_CHANGED/);
  await db.exec('reset role;');await db.exec(notes);await signIn(other);
  assert.equal((await state()).tasks[0].note,'Private','migration is repeatable without erasing notes');
  await db.exec("reset role;update test.clock set value='2026-09-30T15:00:00Z';");await signIn(owner);
  assert.equal((await state()).level,2,'blank notes do not block midnight rewards');
  assert.equal((await db.query('select note from daily_tasks where day=$1 order by position',['2026-09-30'])).rows[0].note,'','history retains the saved note');
  await db.exec('reset role;set role anon;');
  await assert.rejects(state(),e=>e.code==='42501');
  await assert.rejects(db.query('select note from daily_tasks'),e=>e.code==='42501');
  console.log('PASS: optional note persistence, preserved checks/timestamps, blank-note completion/rewards, old clients, validation, stale writes, history, repeat migration and private permissions.');
} finally {await db.close();}
