import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const {Window}=await import(process.env.DOM_MODULE || 'happy-dom');
const w=new Window({url:'https://seungmin.xyz/test.html#calendar',settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true}});
const $=id=>w.document.getElementById(id), pause=()=>new Promise(r=>setTimeout(r,5));
const until=async fn=>{for(let n=0;n<100&&!fn();n++)await pause();assert.ok(fn());};
let played=0,paused=0,rejected=false,timer,reduce=false;
try {
  w.document.write(await readFile(new URL('../test.html',import.meta.url),'utf8'));
  w.lucide={createIcons(){}};
  $('notebook-audio').play=()=>{played++;return rejected?Promise.reject(Error('audio blocked')):Promise.resolve();};$('notebook-audio').pause=()=>paused++;
  w.HTMLElement.prototype.scrollIntoView=()=>{};
  w.matchMedia=()=>({matches:reduce});
  const originalTimeout=w.setTimeout.bind(w);
  w.setTimeout=(fn,delay)=>delay===460?(timer=fn,99):originalTimeout(fn,delay);
  const finish=()=>{timer?.();timer=null;};
  w.journalCloud={user:{id:'owner',email:'test@example.com'},ready:true,version:1,list:async()=>[],save:async()=>{}};
  w.eval(await readFile(new URL('../workout.js',import.meta.url),'utf8'));
  w.eval(await readFile(new URL('../journal.js',import.meta.url),'utf8'));
  await until(()=>$('storage-status').textContent.includes('온라인 저장'));
  const agenda=w.document.querySelector('#calendar .day-agenda'),tasks=$('daily-panel');
  tasks.innerHTML='<input id="draft" value="keep draft">';tasks.hidden=false;
  w.eval(await readFile(new URL('../notebook.js',import.meta.url),'utf8'));
  assert.equal($('schedule-notebook').hidden,true);
  const clickDate=day=>$('month-grid').querySelector(`[data-date="${day}"]`).click();
  const calendarVisible=()=>{assert.equal($('schedule-notebook').hidden,true);assert.equal($('calendar-workspace').hidden,false);};
  w.journalCalendar.selectDate('2026-09-30');
  clickDate('2026-09-30');calendarVisible();
  assert.equal(w.document.activeElement.dataset.date,'2026-09-30','selection keeps keyboard focus on the re-rendered date');
  clickDate('2026-09-29');calendarVisible();assert.equal(w.journalCalendar.range().selected,'2026-09-29');
  assert.equal($('selected-date').textContent,'9월 29일');
  clickDate('2026-09-30');calendarVisible();
  w.journalCalendar.render();calendarVisible();
  clickDate('2026-09-30');
  assert.equal($('schedule-notebook').hidden,false);assert.equal($('calendar-workspace').hidden,true);
  assert.equal(agenda.parentElement,$('notebook-agenda-slot'));assert.equal(tasks.parentElement,$('notebook-tasks-slot'));
  assert.equal(played,0,'opening or loading is silent');
  $('notebook-next').click();assert.equal(w.journalCalendar.range().selected,'2026-10-01');assert.equal(w.journalCalendar.range().month,'2026-10');
  assert.equal(played,1);assert.equal($('notebook-book').dataset.turn,'next');
  $('notebook-next').click();assert.equal(played,1,'rapid turns cannot overlap');finish();
  $('notebook-previous').click();assert.equal(w.journalCalendar.range().selected,'2026-09-30');finish();
  assert.equal($('draft').value,'keep draft');
  $('notebook-sound').click();const before=played;$('notebook-next').click();finish();
  assert.equal(played,before);assert.equal(w.localStorage.getItem('journal-page-sound-v1'),'off');assert.equal(paused,1);
  $('notebook-sound').click();rejected=true;$('notebook-next').click();finish();await pause();
  assert.equal(w.journalCalendar.range().selected,'2026-10-02','blocked audio cannot block navigation');
  const selected=w.journalCalendar.range().selected;
  $('draft').dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));assert.equal(w.journalCalendar.range().selected,selected,'editing arrow keys are not hijacked');
  $('notebook-book').dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true}));finish();assert.equal(w.journalCalendar.range().selected,'2026-10-01');
  $('notebook-tasks-tab').click();assert.equal($('notebook-book').dataset.page,'tasks');
  $('notebook-tasks-tab').dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true}));assert.equal($('notebook-agenda-tab').getAttribute('aria-selected'),'true');
  $('notebook-book').dispatchEvent(new w.PointerEvent('pointerdown',{pointerType:'touch',isPrimary:true,pointerId:1,clientX:250,clientY:200,bubbles:true}));
  $('notebook-book').dispatchEvent(new w.PointerEvent('pointerup',{pointerType:'touch',isPrimary:true,pointerId:1,clientX:50,clientY:205,bubbles:true}));finish();assert.equal(w.journalCalendar.range().selected,'2026-10-02');
  assert.equal(w.journalCalendar.selectDate('2026-02-30'),false);assert.equal(w.journalCalendar.selectDate('bad'),false);
  w.journalCalendar.selectDate('2028-02-28');reduce=true;$('notebook-next').click();assert.equal(w.journalCalendar.range().selected,'2028-02-29');assert.equal($('notebook-book').dataset.turn,undefined);
  $('notebook-next').click();assert.equal(w.journalCalendar.range().selected,'2028-03-01');
  $('calendar-mode').click();assert.equal(agenda.closest('#calendar-workspace'),$('calendar-workspace'));assert.equal(tasks.parentElement,$('calendar-workspace'));assert.equal($('draft').value,'keep draft');
  clickDate('2028-03-01');calendarVisible();
  clickDate('2028-03-01');assert.equal($('schedule-notebook').hidden,false,'repeat selection opens the notebook');
  $('notebook-calendar').click();calendarVisible();
  clickDate('2028-03-01');calendarVisible();
  $('next').click();$('previous').click();clickDate('2028-03-01');calendarVisible();
  $('today').click();const today=w.journalCalendar.range().selected;clickDate(today);calendarVisible();
  $('today').click();clickDate(today);calendarVisible();
  w.journalCalendar.selectDate('2028-03-01');clickDate('2028-03-01');calendarVisible();
  w.dispatchEvent(new w.CustomEvent('journal-view',{detail:'workout'}));
  w.dispatchEvent(new w.CustomEvent('journal-view',{detail:'calendar'}));
  await until(()=>$('storage-status').textContent.includes('온라인 저장'));
  clickDate('2028-03-01');calendarVisible();
  $('notebook-mode').click();$('add-event').click();assert.ok($('editor').open);assert.equal($('record-date').value,'2028-03-01');$('editor').close();
  w.journalCloud.user=null;w.dispatchEvent(new w.Event('journal-account'));await pause();assert.equal($('schedule-notebook').hidden,true);
  const sound=await readFile(new URL('../assets/audio/page-turn.wav',import.meta.url));assert.equal(sound.toString('ascii',0,4),'RIFF');assert.ok(sound.length>1000);
  console.log('PASS: first date click selects, repeat click/button opens notebook, focus and navigation resets, month/leap-year navigation, original views/drafts, bounded animation, real audio/mute/failure, keyboard/touch, picker validation, editor date and logout.');
} finally {await w.happyDOM.close();}
