import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createScrollEntry,entryProgress,entryScene} from '../scroll-entry.js';
const {Window}=await import(process.env.DOM_MODULE || 'happy-dom');
assert.equal(entryProgress(-1,100),0);assert.equal(entryProgress(40,100),.4);assert.equal(entryProgress(120,100),1);assert.equal(entryProgress(0,0),0);
assert.equal(entryProgress(1181.5,1182),1,'fractional mobile scroll reaches the rounded end');
assert.equal(entryProgress(-400,1400),0,'rubber-band scroll cannot reverse the camera past the start');
assert.equal(entryProgress(NaN,1400),0);assert.equal(entryProgress(100,Infinity),0);
assert.equal(entryScene(0)['earth-opacity'],1);assert.equal(entryScene(.5)['korea-opacity'],1);assert.equal(entryScene(1)['seoul-opacity'],1);
for(let i=0;i<=100;i++){
  const scene=entryScene(i/100);
  assert.ok(scene['earth-opacity']+scene['korea-opacity']+scene['seoul-opacity']>=.9,'scene crossfades never leave a blank gap');
  assert.ok(Object.values(scene).every(Number.isFinite));
}
const html=await readFile(new URL('../index.html',import.meta.url),'utf8');
const realm=await readFile(new URL('../realm.js',import.meta.url),'utf8');
assert.equal(/data-auth-mode|회원가입/.test(html),false);assert.equal(/signUp\(/.test(realm),false);
assert.ok(realm.includes('signInWithPassword(credentials)'));
const w=new Window({url:'http://localhost',settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true}});
w.document.write(html);
let active=false,motion=true,entered=0,left=0,offset=0,height=1000,sectionHeight=2400,lastScroll;
const renders=[],section=w.document.getElementById('entry'),button=w.document.getElementById('enter');
Object.defineProperty(section,'offsetHeight',{get:()=>sectionHeight});
Object.defineProperty(section,'offsetTop',{get:()=>0});
Object.defineProperty(section.querySelector('.entry-copy'),'offsetHeight',{get:()=>1000});
Object.defineProperty(w,'scrollY',{get:()=>offset});
Object.defineProperty(w,'innerHeight',{get:()=>height});
w.scrollTo=options=>{lastScroll=options;offset=options.top;w.dispatchEvent(new w.Event('scroll'));};
const tick=()=>new Promise(resolve=>w.requestAnimationFrame(resolve));
const entry=createScrollEntry({section,button,isActive:()=>active,motion:()=>motion,render:p=>renders.push(p),onEnter:()=>entered++,onLeave:()=>left++});
try {
  w.scrollTo({top:1400});await tick();assert.equal(entered,0,'session loading cannot enter');
  offset=0;active=true;entry.reset();
  const upward=new w.WheelEvent('wheel',{deltaY:-100,cancelable:true});w.dispatchEvent(upward);assert.equal(upward.defaultPrevented,true,'top overscroll is blocked');
  const downward=new w.WheelEvent('wheel',{deltaY:100,cancelable:true});w.dispatchEvent(downward);assert.equal(downward.defaultPrevented,false,'normal entry scrolling remains native');
  const pinch=new w.WheelEvent('wheel',{deltaY:-100,cancelable:true});
  // Happy DOM's WheelEvent lacks the MouseEvent modifier-key fields.
  Object.defineProperty(pinch,'ctrlKey',{value:true});w.dispatchEvent(pinch);assert.equal(pinch.defaultPrevented,false,'browser zoom stays available');
  const touch=(type,points)=>{const e=new w.Event(type,{cancelable:true});Object.defineProperty(e,'touches',{value:points.map(clientY=>({clientY}))});w.dispatchEvent(e);return e;};
  touch('touchstart',[200]);assert.equal(touch('touchmove',[250]).defaultPrevented,true,'pulling past the top cannot expose a gap');
  assert.equal(touch('touchmove',[100,200]).defaultPrevented,false,'two-finger zoom is not intercepted');
  touch('touchend',[]);
  w.scrollTo({top:700});await tick();assert.equal(entry.progress,.5);assert.equal(entered,0);
  w.scrollTo({top:280});await tick();assert.equal(entry.progress,.2,'scroll is reversible before entry');
  w.scrollTo({top:1390});await tick();assert.equal(entered,0,'partial scroll does not enter');
  w.scrollTo({top:1400});await tick();assert.equal(entered,1);assert.equal(button.disabled,true);
  w.dispatchEvent(new w.Event('scroll'));await tick();assert.equal(entered,1,'only enters once');
  w.scrollTo({top:700});await tick();assert.equal(left,1);assert.equal(entry.progress,.5);assert.equal(button.disabled,false);
  w.scrollTo({top:0});await tick();assert.equal(left,1,'leaving the end only fires once');assert.equal(entry.progress,0);
  w.scrollTo({top:1400});await tick();assert.equal(entered,2,'can enter again after rewinding');
  entry.reset(1);await tick();assert.equal(offset,1400);assert.equal(entered,2,'direct auth routing positions without a callback loop');
  height=700;w.dispatchEvent(new w.Event('resize'));await tick();assert.equal(offset,1700);assert.equal(entry.progress,1,'viewport resizing keeps the reached form');
  height=1000;w.dispatchEvent(new w.Event('resize'));await tick();assert.equal(offset,1400);assert.equal(left,1);
  w.scrollTo({top:0});await tick();assert.equal(left,2,'direct auth can rewind');
  active=false;entry.reset();w.scrollTo({top:1400});await tick();assert.equal(entered,2,'scrolling forms or map does not enter');
  active=true;motion=false;entry.reset();button.click();await tick();assert.equal(lastScroll.behavior,'instant');assert.equal(entered,3,'keyboard-accessible fallback works without animation');
  motion=true;entry.reset();button.click();await tick();assert.equal(lastScroll.behavior,'smooth');assert.equal(entered,4);
  assert.ok(renders.includes(.5));
  sectionHeight=6200;entry.reset();
  w.scrollTo({top:2600});await tick();assert.equal(entry.progress,.5);assert.equal(entered,4,'long runway cannot enter halfway');
  w.scrollTo({top:5200});await tick();assert.equal(entry.progress,1);assert.equal(entered,5);
  height=700;w.dispatchEvent(new w.Event('resize'));await tick();assert.equal(offset,5500);assert.equal(entry.progress,1);
  w.scrollTo({top:0});await tick();assert.equal(entry.progress,0,'long runway fully reverses after keyboard resize');
  console.log('PASS: native scroll progress/reverse, completion guard, session and stage isolation, keyboard fallback, reduced motion and login-only markup/API.');
} finally {await w.happyDOM.close();}
