import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { parseSubstackFeed, sanitizeSubstackBody, createSubstackReader, watchSubstack } from '../substack.js';
import { emptyFeed, sampleFeed, wrapFeed } from './substack-fixture.mjs';
const { JSDOM } = await import(process.env.JSDOM_MODULE || 'jsdom');
const { window } = new JSDOM(await readFile(new URL('../index.html',import.meta.url),'utf8'),{url:'https://seungmin.xyz/#substack'});
try {
  const document=window.document, Parser=window.DOMParser;
  assert.deepEqual(parseSubstackFeed(emptyFeed,Parser),[]);
  assert.throws(()=>parseSubstackFeed('<html>upstream failed</html>',Parser));
  assert.throws(()=>parseSubstackFeed('<!DOCTYPE rss><rss><channel/></rss>',Parser));
  assert.throws(()=>parseSubstackFeed('x'.repeat(3*1024*1024+1),Parser));
  const posts=parseSubstackFeed(sampleFeed,Parser);
  assert.equal(posts.length,12);assert.equal(posts[0].author,'YSM');
  assert.equal(posts[0].url,'https://tudoryoon.substack.com/p/fixture-0');
  assert.match(posts[0].html,/blockquote/);
  const badLinks=['javascript:alert(1)','https://attacker.invalid/p/x','https://tudoryoon.substack.com@attacker.invalid/p/x','http://tudoryoon.substack.com/p/x'];
  assert.equal(parseSubstackFeed(wrapFeed(badLinks.map(link=>`<item><title>Unsafe</title><link>${link}</link></item>`).join('')),Parser).length,0);
  const duplicate='<item><title>One</title><link>https://tudoryoon.substack.com/p/one</link><pubDate>invalid</pubDate></item>';
  assert.equal(parseSubstackFeed(wrapFeed(duplicate.repeat(2)),Parser).length,1);
  const sanitized=sanitizeSubstackBody(`<script>alert(1)</script><iframe src="https://attacker.invalid"></iframe><form><input name="password"></form><p onclick="alert(1)" style="position:fixed" id="auth">Safe</p><a href="javascript:alert(1)">Bad</a><a href="/p/real">Good</a><img src="https://attacker.invalid/tracker" onerror="alert(1)"><img src="https://substackcdn.com/image/test.png" onerror="alert(1)"><svg onload="alert(1)"></svg>`,document);
  assert.equal(sanitized.querySelector('script,iframe,form,input,svg,[onclick],[onerror],[style],[id]'),null);
  assert.equal(sanitized.querySelectorAll('img').length,1);
  assert.equal(sanitized.querySelector('a').hasAttribute('href'),false);
  assert.equal(sanitized.querySelectorAll('a')[1].href,'https://tudoryoon.substack.com/p/real');
  assert.equal(sanitized.querySelectorAll('a')[1].rel,'noopener noreferrer');
  assert.equal(sanitized.querySelector('img').referrerPolicy,'no-referrer');
  let attempts=0,fail=true,release;
  const root=document.getElementById('substack-content');
  const reader=createSubstackReader(root,async(url,options)=>{
    attempts++;assert.equal(url,'/api/substack');assert.equal(options.credentials,'omit');assert.equal(options.cache,'no-store');
    if(fail)throw new Error('offline');
    await new Promise(resolve=>{release=resolve;});
    return new Response(sampleFeed);
  });
  assert.equal(attempts,0,'feed is lazy and does not load for other pages');
  await reader.load();assert.equal(root.getAttribute('aria-busy'),'false');
  assert.equal(document.getElementById('substack-retry').hidden,false);
  fail=false;document.getElementById('substack-retry').click();const first=reader.load(),second=reader.load();assert.equal(attempts,2,'retry and concurrent calls deduplicate');release();await first;await second;
  assert.equal(root.querySelectorAll('#substack-posts button').length,12);
  assert.equal(document.getElementById('substack-status').textContent,'');
  const firstButton=root.querySelector('#substack-posts button');root.scrollTop=130;firstButton.click();
  assert.equal(document.getElementById('substack-posts').hidden,true);
  assert.equal(document.getElementById('substack-article').hidden,false);
  assert.equal(document.getElementById('substack-article-title').textContent,posts[0].title);
  assert.equal(document.getElementById('substack-article-body').querySelector('script'),null);
  document.getElementById('substack-back').click();
  assert.equal(root.scrollTop,130);assert.equal(document.activeElement,firstButton);
  await reader.load();assert.equal(attempts,2,'recent results are reused');
  assert.equal(root.lastElementChild.className,'substack-footer','profile address remains last');
  assert.equal(root.lastElementChild.querySelector('a').href,'https://substack.com/@tudoryoon');
  let checks=0,hidden=false,interval=null;
  Object.defineProperty(document,'hidden',{get:()=>hidden});
  window.setInterval=(callback,ms)=>{assert.equal(ms,300000);interval=callback;return 1;};
  window.clearInterval=()=>{interval=null;};
  document.body.dataset.stage='home';
  const dispose=watchSubstack({load(){checks++;}},document);
  assert.equal(checks,0);assert.equal(interval,null);
  document.body.dataset.stage='substack';window.dispatchEvent(new window.Event('realm-view'));
  assert.equal(checks,1);interval();assert.equal(checks,2);
  hidden=true;interval();assert.equal(checks,2,'background tabs do not poll');
  hidden=false;document.dispatchEvent(new window.Event('visibilitychange'));assert.equal(checks,3);
  document.body.dataset.stage='auth';window.dispatchEvent(new window.Event('realm-view'));
  assert.equal(interval,null);window.dispatchEvent(new window.Event('focus'));assert.equal(checks,3,'private routes do not fetch');
  dispose();document.body.dataset.stage='substack';window.dispatchEvent(new window.Event('realm-view'));assert.equal(checks,3);
  console.log('PASS: RSS parsing/sorting/limits, safe links, DOMPurify sanitization, lazy fetch, loading/failure/retry, list/detail/back/focus, cache and bottom profile link.');
} finally {window.close();}
