require 'csv'
require 'json'

# T-DATA mixes infrastructure sections and passenger-facing lines.
groups = {
  '1호선'=>%w[1호선 경부선 경인선 장항선], '2호선'=>%w[2호선],
  '3호선'=>%w[3호선 일산선], '4호선'=>%w[4호선 과천선 안산선 진접선],
  '5호선'=>%w[5호선], '6호선'=>%w[6호선], '7호선'=>%w[7호선 7호선(인천)],
  '8호선'=>%w[8호선 별내선], '9호선'=>%w[9호선 9호선(연장)],
  '경의중앙선'=>%w[경의중앙선 중앙선]
}
renames = {'화전'=>'한국항공대', '지제'=>'평택지제', '뚝섬유원지'=>'자양', '총신대입구'=>'총신대입구(이수)', '이수'=>'총신대입구(이수)'}
stations = {}
CSV.read(ARGV.fetch(0), headers:true, encoding:'bom|utf-8').each do |row|
  code, raw_name, section, lng, lat = row.fields
  lines = groups.select { |_, sections| sections.include?(section) }.keys
  if section == '경원선'
    lines << ((1008..1014).include?(code.to_i) ? '경의중앙선' : '1호선')
  end
  lines << '1호선' if %w[1015 0412].include?(code) # 회기, 창동
  lines << '2호선' if code == '2519' # 까치산 (신정지선)
  lines << '경의중앙선' if %w[1003 1953].include?(code) # 용산, 대곡
  next if lines.empty?
  name = raw_name.sub(/\(.*\)$/, '')
  name = renames.fetch(name, name)
  # These homonyms are different places, not transfer stations.
  key = %w[신촌 양평].include?(name) ? "#{name}-#{lines.first}" : name
  station = stations[key] ||= {name:name, lines:[], sourceIds:[], coordinates:[lng.to_f, lat.to_f]}
  dx = (station[:coordinates][0] - lng.to_f) * 88000
  dy = (station[:coordinates][1] - lat.to_f) * 111000
  raise "Review distant namesake: #{key}" if Math.hypot(dx,dy) > 1100
  station[:lines] |= lines
  station[:sourceIds] |= [code]
end
# Dorasan is outside the fare-master CSV; it is reservation-only, not a normal daily stop.
stations['도라산'] = {name:'도라산', lines:['경의중앙선'], sourceIds:['korail-dorasan'], note:'민통선 구간 · 사전 예약과 운행일 확인 필요'}
stations['임진강'][:note] = '운행 횟수가 적은 구간 · 시간표 확인 필요'
stations['운천'][:note] = '운행 횟수가 적은 구간 · 시간표 확인 필요'
data = stations.values.map do |s|
  s[:sourceIds].sort!
  s[:id] = 'station-' + s[:sourceIds].first
  s[:lines].sort_by! { |line| groups.keys.index(line) }
  s
end.sort_by { |s| s[:id] }
File.write(ARGV.fetch(1), "// Generated by scripts/build-stations.rb. Sources: data/stations.md.\nexport const STATIONS = Object.freeze(#{JSON.pretty_generate(data)}.map(station => Object.freeze({...station, lines:Object.freeze(station.lines)})));\n")
puts JSON.generate(count:data.length, byLine:groups.keys.to_h { |line| [line, data.count { |s| s[:lines].include?(line) }] })
